// Auto-generated by build/build_data.py — do not edit by hand.
window.TINYNORD_DATA = {
"products": [
{
"code": "305324",
"name": "Baby bathtub 84 cm",
"category": "bathroom",
"subcategory": "Bathtub",
"tag": "Ergonomic baby bathtub with safe non-slip base",
"description": "Baby bathtub with ergonomic comfort for baby and a safe non-slip base. Lightweight and portable, durable and easy to clean, with a plug for water drainage. Suitable for babies up to 18 months. Bathtub stand sold separately.",
"materials": [],
"dims": "W50 × L84 cm",
"ages": "0–18 months",
"certs": [],
"colors": [
"White",
"Beige",
"Grey"
],
"images": [
"305324_305325_hfktkd.jpg"
]
},
{
"code": "305325",
"name": "Baby bathtub 100 cm",
"category": "bathroom",
"subcategory": "Bathtub",
"tag": "Ergonomic baby bathtub with safe non-slip base",
"description": "Baby bathtub with ergonomic comfort for baby and a safe non-slip base. Lightweight and portable, durable and easy to clean, with a plug for water drainage. Suitable for babies up to 18 months. Bathtub stand sold separately.",
"materials": [],
"dims": "W50 × L100 cm",
"ages": "0–18 months",
"certs": [],
"colors": [
"White",
"Beige",
"Grey"
],
"images": [
"305324_305325_hfktkd.jpg"
]
},
{
"code": "305317",
"name": "Baby bathtub 84 cm beige",
"category": "bathroom",
"subcategory": "Bathtub",
"tag": "Ergonomic baby bathtub in beige",
"description": "Baby bathtub with ergonomic comfort and safe non-slip base. Durable and easy to clean, lightweight and portable, with a plug for water drainage. Suitable for babies up to 18 months.",
"materials": [],
"dims": "W50 × L84 cm",
"ages": "0–18 months",
"certs": [],
"colors": [
"Beige"
],
"images": [
"305317_305318_xs6iqr.jpg"
]
},
{
"code": "305318",
"name": "Baby bathtub 100 cm beige",
"category": "bathroom",
"subcategory": "Bathtub",
"tag": "Ergonomic baby bathtub in beige",
"description": "Baby bathtub with ergonomic comfort and safe non-slip base. Durable and easy to clean, lightweight and portable, with a plug for water drainage. Suitable for babies up to 18 months.",
"materials": [],
"dims": "W50 × L100 cm",
"ages": "0–18 months",
"certs": [],
"colors": [
"Beige"
],
"images": [
"305317_305318_xs6iqr.jpg"
]
},
{
"code": "305331",
"name": "Baby bathtub 84 cm grey",
"category": "bathroom",
"subcategory": "Bathtub",
"tag": "Ergonomic baby bathtub in grey",
"description": "Baby bathtub with ergonomic comfort and safe non-slip base. Durable and easy to clean, lightweight and portable, with a plug for water drainage. Suitable for babies up to 18 months.",
"materials": [],
"dims": "W50 × L84 cm",
"ages": "0–18 months",
"certs": [],
"colors": [
"Grey"
],
"images": [
"305331_305332_egew59.jpg"
]
},
{
"code": "305332",
"name": "Baby bathtub 100 cm grey",
"category": "bathroom",
"subcategory": "Bathtub",
"tag": "Ergonomic baby bathtub in grey",
"description": "Baby bathtub with ergonomic comfort and safe non-slip base. Durable and easy to clean, lightweight and portable, with a plug for water drainage. Suitable for babies up to 18 months.",
"materials": [],
"dims": "W50 × L100 cm",
"ages": "0–18 months",
"certs": [],
"colors": [
"Grey"
],
"images": [
"305331_305332_egew59.jpg"
]
},
{
"code": "299333",
"name": "Foldable bathtub",
"category": "bathroom",
"subcategory": "Foldable bathtub",
"tag": "Compact foldable bathtub – just 10 cm thick",
"description": "Foldable baby bathtub that offers a compact, space-saving solution for bathing your little one. When folded it is just 10 cm thick, ideal for storage and travel. Made from durable, BPA-free materials with a supportive, slip-resistant base and a convenient drain plug for quick water release.",
"materials": [
"BPA free"
],
"dims": "W45 × L75 × H10 cm",
"ages": "0–3 years",
"certs": [],
"colors": [
"Grey"
],
"images": [
"299333_2_kngdlt.jpg",
"299333_2_kngdlt.jpg"
]
},
{
"code": "299332",
"name": "Foldable bathtub seat",
"category": "bathroom",
"subcategory": "Bathtub seat",
"tag": "Foldable bathtub seat with slip-resistant base",
"description": "Bathtub seat that provides a secure and comfortable seating solution for infants during bath time. When folded it is just 8 cm thick. Made from durable BPA-free materials with a supportive, ergonomic design and slip-resistant base. The soft silicone surface adds non-slip support so your little one feels comfortable.",
"materials": [
"BPA free",
"Silicone"
],
"dims": "W30 × L55 × H8 cm",
"ages": "0–12 months",
"certs": [],
"colors": [
"Grey"
],
"images": [
"299332_2_kjzgcz.jpg",
"299332_u0xguj.jpg"
]
},
{
"code": "305321",
"name": "Bathtub seat white",
"category": "bathroom",
"subcategory": "Bathtub seat",
"tag": "Ergonomic bathtub seat with non-slip insert",
"description": "Bathtub seat with ergonomic design for safe support, featuring a non-slip insert for extra stability. Lightweight and easy to place in the tub, durable and easy to clean.",
"materials": [],
"dims": "W24 × L52 cm",
"ages": "",
"certs": [],
"colors": [
"White"
],
"images": [
"305321_pd81fr.jpg"
]
},
{
"code": "305328",
"name": "Bathtub seat grey",
"category": "bathroom",
"subcategory": "Bathtub seat",
"tag": "Ergonomic bathtub seat with non-slip insert",
"description": "Bathtub seat with ergonomic design for safe support, featuring a non-slip insert for extra stability. Lightweight and easy to place in the tub, durable and easy to clean.",
"materials": [],
"dims": "W24 × L52 cm",
"ages": "",
"certs": [],
"colors": [
"Grey"
],
"images": [
"305328_z9rh6o.jpg"
]
},
{
"code": "305314",
"name": "Bathtub seat beige",
"category": "bathroom",
"subcategory": "Bathtub seat",
"tag": "Ergonomic bathtub seat with non-slip insert",
"description": "Bathtub seat with ergonomic design for safe support, featuring a non-slip insert for extra stability. Lightweight and easy to place in the tub, durable and easy to clean.",
"materials": [],
"dims": "W24 × L52 cm",
"ages": "",
"certs": [],
"colors": [
"Beige"
],
"images": [
"305314_rgofcz.jpg"
]
},
{
"code": "305323",
"name": "Step stool white",
"category": "bathroom",
"subcategory": "Step stool",
"tag": "Non-slip step stool with footprint design",
"description": "Step stool with a non-slip footprint design that provides stability for little feet. Helps babies reach sinks, counters and toilets on their own. Made from strong, high-quality material; lightweight and portable, with rounded corners that prevent bumps and scratches.",
"materials": [],
"dims": "W40 × L27 cm",
"ages": "",
"certs": [],
"colors": [
"White"
],
"images": [
"305323_f0tow2.jpg"
]
},
{
"code": "305330",
"name": "Step stool grey",
"category": "bathroom",
"subcategory": "Step stool",
"tag": "Non-slip step stool with footprint design",
"description": "Step stool with a non-slip footprint design that provides stability for little feet. Helps babies reach sinks, counters and toilets on their own. Made from strong, high-quality material; lightweight and portable, with rounded corners that prevent bumps and scratches.",
"materials": [],
"dims": "W40 × L27 cm",
"ages": "",
"certs": [],
"colors": [
"Grey"
],
"images": [
"305330_mfhjyx.jpg"
]
},
{
"code": "305316",
"name": "Step stool beige",
"category": "bathroom",
"subcategory": "Step stool",
"tag": "Non-slip step stool with footprint design",
"description": "Step stool with a non-slip footprint design that provides stability for little feet. Helps babies reach sinks, counters and toilets on their own. Made from strong, high-quality material; lightweight and portable, with rounded corners that prevent bumps and scratches.",
"materials": [],
"dims": "W40 × L27 cm",
"ages": "",
"certs": [],
"colors": [
"Beige"
],
"images": [
"305316_egyj7d.jpg"
]
},
{
"code": "299338",
"name": "Toddler step stool",
"category": "bathroom",
"subcategory": "Step stool",
"tag": "Toddler step stool with anti-slip rubber dots",
"description": "The baby step stool is specially designed for growing toddlers to help them learn new skills independently. It has an anti-slip base and rubber dots for maximum grip, staying in place during use. Perfect for potty training, washing hands, brushing teeth or reaching the sink and kitchen counter.",
"materials": [
"Strong durable plastic"
],
"dims": "W36 × L24 × H14 cm",
"ages": "",
"certs": [],
"colors": [
"White"
],
"images": [
"299338_qxvg26.jpg"
]
},
{
"code": "299337",
"name": "High-back potty",
"category": "bathroom",
"subcategory": "Chamber pot",
"tag": "High-back potty chair with non-slip rubber edges",
"description": "High back potty. Durable and comfortable, allowing your child to sit easily on the potty and lean against the backrest. Easy to use and empty. The rubber edges on the bottom keep the potty firmly on the floor and prevent it from slipping.",
"materials": [],
"dims": "W24 × L28 × H22 cm",
"ages": "",
"certs": [],
"colors": [
"White"
],
"images": [
"299337_2_ag1sqy.jpg",
"299337_xdqbg0.jpg"
]
},
{
"code": "305319",
"name": "Chamber pot white",
"category": "bathroom",
"subcategory": "Chamber pot",
"tag": "Ergonomic chamber pot with non-slip base",
"description": "Chamber pot with ergonomic comfort for baby and a perfect fit for little ones learning potty training. Non-slip base prevents shifting while in use. Lightweight and portable, durable and easy to clean.",
"materials": [],
"dims": "W30 × L34 cm",
"ages": "",
"certs": [],
"colors": [
"White"
],
"images": [
"305319_d1uhwe.jpg"
]
},
{
"code": "305326",
"name": "Chamber pot grey",
"category": "bathroom",
"subcategory": "Chamber pot",
"tag": "Ergonomic chamber pot with non-slip base",
"description": "Chamber pot with ergonomic comfort for baby and a perfect fit for little ones learning potty training. Non-slip base prevents shifting while in use. Lightweight and portable, durable and easy to clean.",
"materials": [],
"dims": "W30 × L34 cm",
"ages": "",
"certs": [],
"colors": [
"Grey"
],
"images": [
"305326_jo080i.jpg"
]
},
{
"code": "305312",
"name": "Chamber pot beige",
"category": "bathroom",
"subcategory": "Chamber pot",
"tag": "Ergonomic chamber pot with non-slip base",
"description": "Chamber pot with ergonomic comfort for baby and a perfect fit for little ones learning potty training. Non-slip base prevents shifting while in use. Lightweight and portable, durable and easy to clean.",
"materials": [],
"dims": "W30 × L34 cm",
"ages": "",
"certs": [],
"colors": [
"Beige"
],
"images": [
"305312_fsfew3.jpg"
]
},
{
"code": "305322",
"name": "Toilet trainer white",
"category": "bathroom",
"subcategory": "Toilet trainer",
"tag": "Smooth-edged toilet trainer with non-slip base",
"description": "Toilet trainer that helps toddlers transition from potty to toilet. Smooth edges and ergonomic shapes, fits most standard toilets securely. Non-slip base prevents shifting while in use.",
"materials": [],
"dims": "W30 × L40 cm",
"ages": "",
"certs": [],
"colors": [
"White"
],
"images": [
"305322_wxoy3z.jpg"
]
},
{
"code": "305329",
"name": "Toilet trainer grey",
"category": "bathroom",
"subcategory": "Toilet trainer",
"tag": "Smooth-edged toilet trainer with non-slip base",
"description": "Toilet trainer that helps toddlers transition from potty to toilet. Smooth edges and ergonomic shapes, fits most standard toilets securely. Non-slip base prevents shifting while in use.",
"materials": [],
"dims": "W30 × L40 cm",
"ages": "",
"certs": [],
"colors": [
"Grey"
],
"images": [
"305329_niy5qy.jpg"
]
},
{
"code": "305315",
"name": "Toilet trainer beige",
"category": "bathroom",
"subcategory": "Toilet trainer",
"tag": "Smooth-edged toilet trainer with non-slip base",
"description": "Toilet trainer that helps toddlers transition from potty to toilet. Smooth edges and ergonomic shapes, fits most standard toilets securely. Non-slip base prevents shifting while in use.",
"materials": [],
"dims": "W30 × L40 cm",
"ages": "",
"certs": [],
"colors": [
"Beige"
],
"images": [
"305315_bariuf.jpg"
]
},
{
"code": "303528",
"name": "BUNITA wash cloth mint",
"category": "bathroom",
"subcategory": "Bathroom accessories",
"tag": "Cotton/bamboo wash cloth that doubles as a hand puppet",
"description": "This cute wash cloth is made of cotton/bamboo terry fabric. Soft on the baby's skin, it cleans gently and makes everyday bathing fun. The cloth can be used as a hand puppet in addition to bathing — a real eye-catcher and an ideal gift for a birth or birthday.",
"materials": [
"60% Cotton",
"40% Bamboo"
],
"dims": "13 × 24 cm",
"ages": "",
"certs": [],
"colors": [
"Mint"
],
"images": [
"303528_f539jr.jpg"
]
},
{
"code": "303527",
"name": "BUNITA wash cloth beige",
"category": "bathroom",
"subcategory": "Bathroom accessories",
"tag": "Cotton/bamboo wash cloth that doubles as a hand puppet",
"description": "This cute wash cloth is made of cotton/bamboo terry fabric. Soft on the baby's skin, it cleans gently and makes everyday bathing fun. The cloth can be used as a hand puppet in addition to bathing — a real eye-catcher and an ideal gift for a birth or birthday.",
"materials": [
"60% Cotton",
"40% Bamboo"
],
"dims": "13 × 24 cm",
"ages": "",
"certs": [],
"colors": [
"Beige"
],
"images": [
"303527_lcmkge.jpg"
]
},
{
"code": "303524",
"name": "BATHY hooded towel mint",
"category": "bathroom",
"subcategory": "Bathroom accessories",
"tag": "Soft hooded bath towel in cotton/bamboo terry",
"description": "After bath time, gently wrap your baby in this soft and adorable hooded towel. Made from absorbent cotton/bamboo terry fabric, gentle on the skin and very absorbent. Baby will feel safe, warm and secure inside the 75 × 75 cm bath towel and look super sweet with the hood on.",
"materials": [
"60% Cotton",
"40% Bamboo"
],
"dims": "75 × 75 cm",
"ages": "",
"certs": [],
"colors": [
"Mint"
],
"images": [
"303524_tpwef1.jpg"
]
},
{
"code": "303523",
"name": "BATHY hooded towel beige",
"category": "bathroom",
"subcategory": "Bathroom accessories",
"tag": "Soft hooded bath towel in cotton/bamboo terry",
"description": "After bath time, gently wrap your baby in this soft and adorable hooded towel. Made from absorbent cotton/bamboo terry fabric, gentle on the skin and very absorbent. Baby will feel safe, warm and secure inside the 75 × 75 cm bath towel and look super sweet with the hood on.",
"materials": [
"60% Cotton",
"40% Bamboo"
],
"dims": "75 × 75 cm",
"ages": "",
"certs": [],
"colors": [
"Beige"
],
"images": [
"303523_jabaus.jpg"
]
},
{
"code": "303526",
"name": "BAILI hooded poncho mint",
"category": "bathroom",
"subcategory": "Bathroom accessories",
"tag": "Hooded poncho in light, breathable cotton/bamboo terry",
"description": "This hooded poncho is made of cotton/bamboo terry fabric — light, absorbent and breathable. Perfect for drying quickly and protecting the child from the cold after a swim. The hood and loose fit allow little ones to move freely while drying and staying warm. Easy to put on and take off.",
"materials": [
"60% Cotton",
"40% Bamboo"
],
"dims": "50 × 50 cm",
"ages": "",
"certs": [],
"colors": [
"Mint"
],
"images": [
"303526_1_vletaj.jpg",
"303526_2_moijtf.jpg"
]
},
{
"code": "303525",
"name": "BAILI hooded poncho beige",
"category": "bathroom",
"subcategory": "Bathroom accessories",
"tag": "Hooded poncho in light, breathable cotton/bamboo terry",
"description": "This hooded poncho is made of cotton/bamboo terry fabric — light, absorbent and breathable. Perfect for drying quickly and protecting the child from the cold after a swim. The hood and loose fit allow little ones to move freely while drying and staying warm. Easy to put on and take off.",
"materials": [
"60% Cotton",
"40% Bamboo"
],
"dims": "50 × 50 cm",
"ages": "",
"certs": [],
"colors": [
"Beige"
],
"images": [
"303525_1_usngzg.jpg",
"303525_2_lwbnq4.jpg"
]
},
{
"code": "303530",
"name": "TERRY changing mat towel mint",
"category": "bathroom",
"subcategory": "Changing mat",
"tag": "Light, absorbent changing mat towel in cotton/bamboo",
"description": "This changing mat towel is made of cotton/bamboo terry fabric — light, absorbent and breathable. When changing diapers, place a towel under your baby to keep them warm and dry.",
"materials": [
"60% Cotton",
"40% Bamboo"
],
"dims": "45 × 65 cm",
"ages": "",
"certs": [],
"colors": [
"Mint"
],
"images": [
"303530_1_h1dvgv.jpg",
"303530_2_rzzvak.jpg"
]
},
{
"code": "303529",
"name": "TERRY changing mat towel beige",
"category": "bathroom",
"subcategory": "Changing mat",
"tag": "Light, absorbent changing mat towel in cotton/bamboo",
"description": "This changing mat towel is made of cotton/bamboo terry fabric — light, absorbent and breathable. When changing diapers, place a towel under your baby to keep them warm and dry.",
"materials": [
"60% Cotton",
"40% Bamboo"
],
"dims": "45 × 65 cm",
"ages": "",
"certs": [],
"colors": [
"Beige"
],
"images": [
"303529_1_cavks0.jpg",
"303529_2_zanfba.jpg"
]
},
{
"code": "303522",
"name": "MATEO changing mat",
"category": "bathroom",
"subcategory": "Changing mat",
"tag": "Cosy changing mat with water-repellent surface",
"description": "This changing mat provides a comfortable and safe spot for your little one. Soft, warm fabric ensures a cosy surface, while raised sides help prevent your baby from rolling out. The water-repellent fabric is easy to wipe off and keep clean. The cover has a zip closure and can easily be removed and washed inside out.",
"materials": [
"100% Cotton (shell)",
"100% PU (mattress filling)",
"100% PES (cover filling)"
],
"dims": "50 × 70 cm",
"ages": "0–12 months",
"certs": [],
"colors": [
"Beige"
],
"images": [
"303522_1_nnjpyz.jpg",
"303522_2_gopamm.jpg",
"303522_3_fs6ovy.jpg",
"303522_4_np5fjc.jpg"
]
},
{
"code": "305310",
"name": "MATIO changing mat",
"category": "bathroom",
"subcategory": "Changing mat",
"tag": "Soft changing mat with waterproof, easy-wipe surface",
"description": "Make diaper change time practical with a soft, easy-to-wipe changing mat. The waterproof surface makes it easy to clean.",
"materials": [
"100% phthalate-free PVC (cover)",
"100% Polyurethane (filling)"
],
"dims": "50 × 70 cm",
"ages": "0–12 months",
"certs": [],
"colors": [
"Grey"
],
"images": [
"305310_sl8vfa.jpg"
]
},
{
"code": "305311",
"name": "MATTI changing mat",
"category": "bathroom",
"subcategory": "Changing mat",
"tag": "Light hardback changing mat – just 1200 g",
"description": "Light hardback changing mat is a symbol of safety and modernity. Its exceptional lightness (1200 g) makes it indispensable. Thanks to the waterproof surface, cleaning is easy. Long velcro straps attach the mat stably to the cot, minimising the risk of movement during changing.",
"materials": [
"100% Cotton (cover)",
"100% PU foam (filling)"
],
"dims": "50 × 70 cm",
"ages": "0–12 months",
"certs": [],
"colors": [
"White"
],
"images": [
"305311_bn0u5i.jpg"
]
},
{
"code": "303521",
"name": "COVERY changing mat cover mint",
"category": "bathroom",
"subcategory": "Changing mat",
"tag": "Soft cotton/bamboo changing mat cover",
"description": "Soft cotton/bamboo fabric makes the changing mat more comfortable for the baby and avoids skin contact with the cool surface. Keeps the surface of the changing mat clean. Easily removable thanks to elastic rubber bandages.",
"materials": [
"60% Cotton",
"40% Bamboo"
],
"dims": "50 × 70 cm",
"ages": "",
"certs": [],
"colors": [
"Mint"
],
"images": [
"303521_1_xpi8e8.jpg",
"303521_2_ef64rd.jpg"
]
},
{
"code": "303520",
"name": "COVERY changing mat cover beige",
"category": "bathroom",
"subcategory": "Changing mat",
"tag": "Soft cotton/bamboo changing mat cover",
"description": "Soft cotton/bamboo fabric makes the changing mat more comfortable for the baby and avoids skin contact with the cool surface. Keeps the surface of the changing mat clean. Easily removable thanks to elastic rubber bandages.",
"materials": [
"60% Cotton",
"40% Bamboo"
],
"dims": "50 × 70 cm",
"ages": "",
"certs": [],
"colors": [
"Beige"
],
"images": [
"303520_1_mnmsk8.jpg",
"303520_2_irn1wg.jpg"
]
},
{
"code": "304885",
"name": "MATYA PUR changing mat",
"category": "bathroom",
"subcategory": "Changing mat",
"tag": "PUR foam changing mat with TÜV SÜD safety certification",
"description": "Make every diaper change easier with the PUR Changing Mat. Crafted from soft, non-toxic PUR foam, it offers a warm and comfortable surface that is safe for your baby. Its water-repellent, seamless design prevents bacteria and dirt build-up. The raised edges keep your little one safely in place. Compact and lightweight for small spaces or travel.",
"materials": [
"Moulded PUR foam",
"Phthalate free"
],
"dims": "45 × 70 × 11 cm",
"ages": "0–12 months",
"certs": [
"TÜV SÜD"
],
"colors": [
"Beige"
],
"images": [
"304885_3_qelvjx.jpg",
"304885_2_ima036.jpg",
"304885_3_qelvjx.jpg"
]
},
{
"code": "299355",
"name": "Silicone section plate",
"category": "eating",
"subcategory": "Silicone plates",
"tag": "Section plate with strong suction base",
"description": "Silicone section plate that makes your child's meals a fun and easy experience. Designed with a strong suction base that helps the plate stick to the table. Sections make it simple to serve a variety of foods without mixing.",
"materials": [
"100% food-grade silicone",
"BPA free"
],
"dims": "",
"ages": "6+ months",
"certs": [],
"colors": [
"Beige",
"Mint",
"Rust"
],
"images": [
"299355_2_b0cmxf.jpg",
"299355_3_wvovev.jpg",
"299355_2_b0cmxf.jpg"
]
},
{
"code": "299356",
"name": "Silicone mini bowl beige",
"category": "eating",
"subcategory": "Silicone bowls",
"tag": "Small silicone bowl with suction base",
"description": "Small silicone bowl with suction base. The soft and durable silicone does not slip, and the suction pad at the bottom keeps the bowl securely in place. Microwave and dishwasher safe (-20 °C to 220 °C).",
"materials": [
"100% food-grade silicone",
"BPA free"
],
"dims": "",
"ages": "6+ months",
"certs": [],
"colors": [
"Beige"
],
"images": [
"299356_2_oxfuh1.jpg",
"299356_3_losz7o.jpg",
"299356_3_losz7o.jpg"
]
},
{
"code": "299357",
"name": "Silicone mini bowl mint",
"category": "eating",
"subcategory": "Silicone bowls",
"tag": "Small silicone bowl with suction base",
"description": "Small silicone bowl with suction base. The soft and durable silicone does not slip, and the suction pad at the bottom keeps the bowl securely in place. Microwave and dishwasher safe (-20 °C to 220 °C).",
"materials": [
"100% food-grade silicone",
"BPA free"
],
"dims": "",
"ages": "6+ months",
"certs": [],
"colors": [
"Mint"
],
"images": [
"299357_2_sas8fs.jpg",
"299357_3_bgcib5.jpg",
"299357_3_bgcib5.jpg"
]
},
{
"code": "299365",
"name": "Silicone spoon beige",
"category": "eating",
"subcategory": "Silicone spoons",
"tag": "Silicone-tipped spoon with beech wood handle",
"description": "Designed with a soft silicone tip and beech wood handle. Made from high-quality food-grade silicone, totally free from BPA. Gentle on tender gums, durable and safe to use in the dishwasher.",
"materials": [
"100% food-grade silicone",
"Beech wood",
"BPA free"
],
"dims": "",
"ages": "6+ months",
"certs": [],
"colors": [
"Beige"
],
"images": [
"299365_2_azqhau.jpg",
"299365_2_azqhau.jpg"
]
},
{
"code": "299364",
"name": "Silicone spoon mint",
"category": "eating",
"subcategory": "Silicone spoons",
"tag": "Silicone-tipped spoon with beech wood handle",
"description": "Designed with a soft silicone tip and beech wood handle. Made from high-quality food-grade silicone, totally free from BPA. Gentle on tender gums, durable and safe to use in the dishwasher.",
"materials": [
"100% food-grade silicone",
"Beech wood",
"BPA free"
],
"dims": "",
"ages": "6+ months",
"certs": [],
"colors": [
"Mint"
],
"images": [
"299364_2_qw9szo.jpg",
"299364_2_qw9szo.jpg"
]
},
{
"code": "299366",
"name": "Silicone pre-spoon set beige/mint",
"category": "eating",
"subcategory": "Silicone spoons",
"tag": "Easy-clean pre-spoon set for small hands",
"description": "These pre-spoons are easy to clean and designed for small hands. Made from high-quality food-grade silicone, totally free from BPA. Textured handle enhances motor skills and is gentle on tender gums.",
"materials": [
"100% food-grade silicone",
"BPA free"
],
"dims": "",
"ages": "6+ months",
"certs": [],
"colors": [
"Beige",
"Mint"
],
"images": [
"299366_2_nupfyr.jpg",
"299366_x6jbnv.jpg"
]
},
{
"code": "299367",
"name": "Silicone pre-spoon set beige/rust",
"category": "eating",
"subcategory": "Silicone spoons",
"tag": "Easy-clean pre-spoon set for small hands",
"description": "These pre-spoons are easy to clean and designed for small hands. Made from high-quality food-grade silicone, totally free from BPA. Textured handle enhances motor skills and is gentle on tender gums.",
"materials": [
"100% food-grade silicone",
"BPA free"
],
"dims": "",
"ages": "6+ months",
"certs": [],
"colors": [
"Beige",
"Rust"
],
"images": [
"299367_2_tlqspm.jpg",
"299367_uufa32.jpg"
]
},
{
"code": "299360",
"name": "Silicone sippy cup mint",
"category": "eating",
"subcategory": "Silicone cups",
"tag": "Two-handle sippy cup with no-spill lid",
"description": "Silicone sippy cup with a cute design. The lid keeps liquid from spilling. The two-handle design makes the cup more secure for a child's hand. Durable, dishwasher safe.",
"materials": [
"100% food-grade silicone",
"BPA free"
],
"dims": "",
"ages": "6+ months",
"certs": [],
"colors": [
"Mint"
],
"images": [
"299360_2_q7vmkk.jpg",
"299360_2_q7vmkk.jpg"
]
},
{
"code": "299359",
"name": "Silicone sippy cup rust",
"category": "eating",
"subcategory": "Silicone cups",
"tag": "Two-handle sippy cup with no-spill lid",
"description": "Silicone sippy cup with a cute design. The lid keeps liquid from spilling. The two-handle design makes the cup more secure for a child's hand. Durable, dishwasher safe.",
"materials": [
"100% food-grade silicone",
"BPA free"
],
"dims": "",
"ages": "6+ months",
"certs": [],
"colors": [
"Rust"
],
"images": [
"299359_2_fopvun.jpg",
"299359_ernr6t.jpg"
]
},
{
"code": "299358",
"name": "Silicone food pouch",
"category": "eating",
"subcategory": "Silicone food pouches",
"tag": "Reusable silicone food pouch for mess-free meals",
"description": "Let your little one eat anywhere, anytime with the silicone food pouch. Made of high-quality food-grade silicone that can be reused over and over again — a sustainable alternative to disposable pouches. Microwave and dishwasher safe (-20 °C to 220 °C).",
"materials": [
"100% food-grade silicone",
"BPA free"
],
"dims": "",
"ages": "4+ months",
"certs": [],
"colors": [
"Mint"
],
"images": [
"299358_2_mtxkrb.jpg",
"299358_2_mtxkrb.jpg"
]
},
{
"code": "299361",
"name": "Silicone food feeder",
"category": "eating",
"subcategory": "Silicone feeders",
"tag": "Silicone food feeder that soothes teething gums",
"description": "The baby food feeder is the perfect way to introduce babies to fruits, vegetables or puree without the risk of choking. Soothes teething gums while feeding, easy to use and clean.",
"materials": [
"100% food-grade silicone",
"BPA free"
],
"dims": "",
"ages": "4+ months",
"certs": [],
"colors": [
"Beige"
],
"images": [
"299361_2_nbbdzu.jpg",
"299361_2_nbbdzu.jpg"
]
},
{
"code": "299362",
"name": "Food feeder PP & silicone",
"category": "eating",
"subcategory": "Silicone feeders",
"tag": "Safe PP and silicone feeder for solid foods",
"description": "Convenient and safe food feeder designed to introduce solid foods to babies. Made from durable food-grade polypropylene (PP) and soft silicone that lets babies safely chew on small portions. Reduces the risk of choking, easy to use and clean, and soothes teething gums.",
"materials": [
"Polypropylene (PP)",
"Soft silicone",
"BPA free"
],
"dims": "",
"ages": "4+ months",
"certs": [],
"colors": [
"Mint"
],
"images": [
"299362_2_c5wrmw.jpg",
"299362_2_c5wrmw.jpg"
]
},
{
"code": "299371",
"name": "Silicone teether mint/blue",
"category": "eating",
"subcategory": "Silicone teethers",
"tag": "Textured silicone teether for soothing gums",
"description": "Silicone teether that helps soothe your little one's gums. Easy to hold and features textured sides that provide extra relief with every chomp. Durable, dishwasher safe.",
"materials": [
"Food-grade silicone",
"BPA free"
],
"dims": "",
"ages": "3+ months",
"certs": [],
"colors": [
"Mint",
"Blue"
],
"images": [
"299371_2_jpb9mi.jpg",
"299371_2_jpb9mi.jpg"
]
},
{
"code": "299370",
"name": "Silicone teether lavender/pink",
"category": "eating",
"subcategory": "Silicone teethers",
"tag": "Textured silicone teether for soothing gums",
"description": "Silicone teether that helps soothe your little one's gums. Easy to hold and features textured sides that provide extra relief with every chomp. Durable, dishwasher safe.",
"materials": [
"Food-grade silicone",
"BPA free"
],
"dims": "",
"ages": "3+ months",
"certs": [],
"colors": [
"Lavender",
"Pink"
],
"images": [
"299370_2_bmr2gz.jpg",
"299370_2_bmr2gz.jpg"
]
},
{
"code": "299372",
"name": "Silicone teether beige",
"category": "eating",
"subcategory": "Silicone teethers",
"tag": "Textured silicone teether for soothing gums",
"description": "Silicone teether that helps soothe your little one's gums. Easy to hold and features textured sides that provide extra relief with every chomp. Durable, dishwasher safe.",
"materials": [
"Food-grade silicone",
"BPA free"
],
"dims": "",
"ages": "3+ months",
"certs": [],
"colors": [
"Beige"
],
"images": [
"299372_2_yj1zj7.jpg",
"299372_2_yj1zj7.jpg"
]
},
{
"code": "299369",
"name": "Silicone spoon beige/mint/blue",
"category": "eating",
"subcategory": "Silicone spoons",
"tag": "Soft silicone spoon with beech wood handle",
"description": "Designed with a soft silicone tip and beech wood handle. Made from high-quality food-grade silicone, totally free from BPA. Durable and long-lasting.",
"materials": [
"100% food-grade silicone",
"Beech wood",
"BPA free"
],
"dims": "",
"ages": "3+ months",
"certs": [],
"colors": [
"Beige",
"Mint",
"Blue"
],
"images": [
"299369_2_xshwhy.jpg",
"299369_2_xshwhy.jpg"
]
},
{
"code": "299368",
"name": "Silicone spoon beige/pink/lavender",
"category": "eating",
"subcategory": "Silicone spoons",
"tag": "Soft silicone spoon with beech wood handle",
"description": "Designed with a soft silicone tip and beech wood handle. Made from high-quality food-grade silicone, totally free from BPA. Durable and long-lasting.",
"materials": [
"100% food-grade silicone",
"Beech wood",
"BPA free"
],
"dims": "",
"ages": "3+ months",
"certs": [],
"colors": [
"Beige",
"Pink",
"Lavender"
],
"images": [
"299368_qolyji.jpg"
]
},
{
"code": "299363",
"name": "Silicone finger toothbrush",
"category": "eating",
"subcategory": "Silicone toothbrushes",
"tag": "Finger toothbrush to clean and massage gumline",
"description": "Finger toothbrush. Start your baby's healthy and hygienic oral habits from the gumline — clean and massage. Hand wash in warm water. Replace every 3–4 months.",
"materials": [
"100% food-grade silicone",
"BPA free"
],
"dims": "",
"ages": "3+ months",
"certs": [],
"colors": [
"Mint",
"Beige"
],
"images": [
"299363_2_w5hjfm.jpg",
"299363_b5wsf3.jpg"
]
},
{
"code": "304346",
"name": "Baby bib",
"category": "eating",
"subcategory": "Baby bibs",
"tag": "Soft cotton baby bib",
"description": "A soft baby bib made for everyday meals and play. Practical and easy to wash.",
"materials": [],
"dims": "",
"ages": "",
"certs": [],
"colors": [],
"images": [
"304346_1_kesmht.jpg",
"304346_2_zvutdh.jpg"
]
},
{
"code": "304347",
"name": "Baby bib",
"category": "eating",
"subcategory": "Baby bibs",
"tag": "Soft cotton baby bib",
"description": "A soft baby bib made for everyday meals and play. Practical and easy to wash.",
"materials": [],
"dims": "",
"ages": "",
"certs": [],
"colors": [],
"images": [
"304347_1_n3sjxf.jpg",
"304347_2_lbwvtk.jpg"
]
},
{
"code": "297295",
"name": "LEON dropside cot",
"category": "bedroom",
"subcategory": "Cot beds",
"tag": "Adjustable dropside cot in timeless pine wood",
"description": "Dropside cot made of New Zealand pine wood. Adjustable to three different heights, ensuring your child's safety during the rapid growth period. One side of the bed can be lowered, allowing your child to be taken in and out easily. Once your toddler is ready for a bigger bed, you can remove the side rail and either add the toddler guard panel or leave one side completely open. Sides are covered with protective teething rails to extend its life.",
"materials": [
"100% pine wood"
],
"dims": "W124 × L65 × H89 cm",
"ages": "Child's max. weight: 25 kg",
"certs": [
"EN 716-1:2017+AC:2019"
],
"colors": [
"White"
],
"images": [
"297295_1__LEON_mpwr1m.jpg",
"297295_2__LEON_ia0mda.jpg",
"297295_3__LEON_azwp8n.jpg",
"297295_4__LEON_d9wl8p.jpg"
]
},
{
"code": "297297",
"name": "LASSY cot bed natural",
"category": "bedroom",
"subcategory": "Cot beds",
"tag": "Height-adjustable pine cot bed for growing babies",
"description": "A cot bed made of New Zealand pine wood. Adjustable to three different heights for safety during the rapid growth period. The pine wood design is timeless and suitable for any interior.",
"materials": [
"100% pine wood"
],
"dims": "W124 × L64 × H81 cm",
"ages": "Child's max. weight: 25 kg",
"certs": [
"EN 716-1:2017+AC:2019"
],
"colors": [
"Natural"
],
"images": [
"297297_1__LASSY_natural_ceq2z6.jpg",
"297297_2__LASSY_natural_vebsyn.jpg"
]
},
{
"code": "297296",
"name": "LASSY cot bed white",
"category": "bedroom",
"subcategory": "Cot beds",
"tag": "Height-adjustable pine cot bed for growing babies",
"description": "A cot bed made of New Zealand pine wood. Adjustable to three different heights for safety during the rapid growth period. The pine wood design is timeless and suitable for any interior.",
"materials": [
"100% pine wood"
],
"dims": "W124 × L64 × H81 cm",
"ages": "Child's max. weight: 25 kg",
"certs": [
"EN 716-1:2017+AC:2019"
],
"colors": [
"White"
],
"images": [
"297296_1__LASSY_white_iyfepe.jpg",
"297296_2__LASSY_req04y.jpg"
]
},
{
"code": "305018",
"name": "AIRY mattress",
"category": "bedroom",
"subcategory": "Mattresses",
"tag": "Premium two-sided coconut & foam mattress with 3D ventilation",
"description": "Two-sided mattress made from high-quality, child-safe materials with a soft, removable cover for easy cleaning. One side of the polyurethane foam features natural coconut, the other side has horizontal ventilation channels combined with 3D knitted fabric for excellent airflow.",
"materials": [
"Natural coconut fibre",
"Natural latex",
"Polyurethane foam (PUR)",
"100% polyester fleece",
"100% polyester cover",
"100% polypropylene"
],
"dims": "120 × 60 × 10 cm",
"ages": "0+ months",
"certs": [
"OEKO-TEX Standard 100"
],
"colors": [
"White"
],
"images": [
"305018_hugdou.jpg"
]
},
{
"code": "305295",
"name": "COCO mattress",
"category": "bedroom",
"subcategory": "Mattresses",
"tag": "Two-sided coconut fibre & foam mattress",
"description": "The two-sided mattress is made from high-quality, child-safe materials with a soft, removable cover. One side features natural coconut fibre, the other side is made of resilient polyurethane foam for a softer feel.",
"materials": [
"Natural coconut fibre",
"Natural latex",
"Polyurethane foam (PUR)",
"100% polyester fleece",
"100% polyester cover",
"100% polypropylene"
],
"dims": "120 × 60 × 9.5 cm",
"ages": "0+ months",
"certs": [
"OEKO-TEX Standard 100"
],
"colors": [
"White"
],
"images": [
"305295_cblqoq.jpg"
]
},
{
"code": "305019",
"name": "SLIMMY mattress",
"category": "bedroom",
"subcategory": "Mattresses",
"tag": "Lightweight foam mattress with breathable cover",
"description": "The mattress is made from high-quality, child-safe materials and features a soft, removable cover. Its core is crafted from durable polyurethane foam (PUR), providing stable yet flexible support. Lightweight and breathable for a fresh, hygienic sleeping environment.",
"materials": [
"Polyurethane foam (PUR)",
"100% polyester fleece",
"100% polyester cover",
"100% polypropylene"
],
"dims": "120 × 60 × 6 cm",
"ages": "0+ months",
"certs": [
"OEKO-TEX Standard 100"
],
"colors": [
"White"
],
"images": [
"305019_ruprgy.jpg"
]
},
{
"code": "1110",
"name": "ROLLY travel mattress",
"category": "bedroom",
"subcategory": "Mattresses",
"tag": "Portable travel mattress with 3D-knit airflow side and carry bag",
"description": "The Travel Mattress combines comfort, practicality, and portability in one smart design. Lightweight with a soft, removable cover; one side features 3D knitted fabric for excellent airflow. Polyurethane foam core provides comfort and support. Convenient carry bag included.",
"materials": [
"Polyurethane foam (PUR)",
"100% polyester fleece",
"100% polyester cover",
"100% polypropylene"
],
"dims": "120 × 60 × 5 cm",
"ages": "0+ months",
"certs": [
"OEKO-TEX Standard 100"
],
"colors": [
"White"
],
"images": [
"1110_q46jhd.jpg"
]
},
{
"code": "305016",
"name": "FOLDY travel mattress grey",
"category": "bedroom",
"subcategory": "Mattresses",
"tag": "Foldable travel foam mattress",
"description": "Give your child a comfortable night's sleep anywhere with this foldable travel mattress. Removable cover for easy cleaning, polyurethane foam core for stable yet flexible support. Lightweight and easy to fold — ideal for travel, storage, or everyday use.",
"materials": [
"100% polyurethane foam",
"100% polyester cover"
],
"dims": "120 × 60 × 5.5 cm",
"ages": "0+ months",
"certs": [
"OEKO-TEX Standard 100"
],
"colors": [
"Grey"
],
"images": [
"305016_1_mgm1nl.jpg",
"305016_2_ydehuf.png",
"305016_3_jkcpql.jpg",
"305016_4_yskzha.png"
]
},
{
"code": "305017",
"name": "FOLDY travel mattress white",
"category": "bedroom",
"subcategory": "Mattresses",
"tag": "Foldable travel foam mattress",
"description": "Give your child a comfortable night's sleep anywhere with this foldable travel mattress. Removable cover for easy cleaning, polyurethane foam core for stable yet flexible support. Lightweight and easy to fold — ideal for travel, storage, or everyday use.",
"materials": [
"100% polyurethane foam",
"100% polyester cover"
],
"dims": "120 × 60 × 5.5 cm",
"ages": "0+ months",
"certs": [
"OEKO-TEX Standard 100"
],
"colors": [
"White"
],
"images": [
"305017_1_stw0hd.png",
"305017_2_tobpr9.png",
"305017_3_xn7hy0.jpg",
"305017_4_je7f00.png"
]
},
{
"code": "305012",
"name": "Duvet & pillow set",
"category": "bedroom",
"subcategory": "Duvet & pillow",
"tag": "Soft cotton duvet and pillow set",
"description": "Set includes a duvet and a pillow with a 100% cotton shell and polyester filling. Soft, breathable and gentle on delicate skin.",
"materials": [
"100% Cotton shell",
"100% Polyester filling"
],
"dims": "Duvet 100 × 130 cm; Pillow 60 × 40 cm",
"ages": "",
"certs": [],
"colors": [
"White"
],
"images": [
"305012_lkbkhz.jpg"
]
},
{
"code": "305013",
"name": "Cotton duvet",
"category": "bedroom",
"subcategory": "Duvet & pillow",
"tag": "Soft and breathable cotton duvet",
"description": "Cotton duvet with a 100% cotton shell and polyester filling. Soft, breathable and gentle on delicate skin.",
"materials": [
"100% Cotton shell",
"100% Polyester filling"
],
"dims": "100 × 130 cm",
"ages": "",
"certs": [],
"colors": [
"White"
],
"images": [
"305013_uocx18.jpg"
]
},
{
"code": "305014",
"name": "Cotton pillow",
"category": "bedroom",
"subcategory": "Duvet & pillow",
"tag": "Soft cotton pillow gentle on delicate baby skin",
"description": "Cotton pillow with a 100% cotton shell and polyester filling. Soft, breathable and gentle on delicate skin.",
"materials": [
"100% Cotton shell",
"100% Polyester filling"
],
"dims": "60 × 40 cm",
"ages": "",
"certs": [],
"colors": [
"White"
],
"images": [
"305014_kbqwty.jpg"
]
},
{
"code": "305015",
"name": "Wedge pillow",
"category": "bedroom",
"subcategory": "Duvet & pillow",
"tag": "Gentle wedge pillow for elevated infant sleep",
"description": "Wedge pillow made from 100% polyester with polyester filling. Soft and gentle on delicate skin.",
"materials": [
"100% Polyester shell",
"100% Polyester filling"
],
"dims": "60 × 40 cm",
"ages": "",
"certs": [],
"colors": [
"White"
],
"images": [
"305015_1_llvnw1.jpg",
"305015_2_jyojin.jpg"
]
},
{
"code": "228531",
"name": "Duvet & pillow",
"category": "bedroom",
"subcategory": "Duvet & pillow",
"tag": "Cotton duvet & pillow set",
"description": "Cotton duvet and pillow with polyester filling. Soft and breathable.",
"materials": [
"100% Cotton shell",
"100% Polyester filling"
],
"dims": "",
"ages": "",
"certs": [],
"colors": [
"White"
],
"images": [
"228531_2_z069ep.jpg"
]
},
{
"code": "305006",
"name": "Bamboo fitted sheet white",
"category": "bedroom",
"subcategory": "Sheets",
"tag": "Temperature-regulating bamboo fitted sheet",
"description": "Fitted sheet made of 100% bamboo with a strong, flexible elastic edge. Bamboo regulates temperature — cool in summer and warm in winter. Suits higher mattresses (up to 14.5 cm) and retains shape after washing.",
"materials": [
"100% Bamboo"
],
"dims": "60 × 120 cm",
"ages": "",
"certs": [],
"colors": [
"White"
],
"images": [
"305006_l7xfhf.jpg"
]
},
{
"code": "305005",
"name": "Bamboo fitted sheet beige",
"category": "bedroom",
"subcategory": "Sheets",
"tag": "Temperature-regulating bamboo fitted sheet",
"description": "Fitted sheet made of 100% bamboo with a strong, flexible elastic edge. Bamboo regulates temperature — cool in summer and warm in winter. Suits higher mattresses (up to 14.5 cm) and retains shape after washing.",
"materials": [
"100% Bamboo"
],
"dims": "60 × 120 cm",
"ages": "",
"certs": [],
"colors": [
"Beige"
],
"images": [
"305005_wpbqus.jpg"
]
},
{
"code": "305003",
"name": "Bamboo fitted sheet green",
"category": "bedroom",
"subcategory": "Sheets",
"tag": "Temperature-regulating bamboo fitted sheet",
"description": "Fitted sheet made of 100% bamboo with a strong, flexible elastic edge. Bamboo regulates temperature — cool in summer and warm in winter. Suits higher mattresses (up to 14.5 cm) and retains shape after washing.",
"materials": [
"100% Bamboo"
],
"dims": "60 × 120 cm",
"ages": "",
"certs": [],
"colors": [
"Green"
],
"images": [
"305003_jvqomo.jpg"
]
},
{
"code": "305009",
"name": "Cotton fitted sheet white",
"category": "bedroom",
"subcategory": "Sheets",
"tag": "Soft 100% cotton fitted sheet",
"description": "Cotton fitted sheet made of 100% high-quality cotton with a strong elastic edge. Suits higher mattresses (up to 14.5 cm) and retains shape after washing.",
"materials": [
"100% Cotton"
],
"dims": "60 × 120 cm",
"ages": "",
"certs": [],
"colors": [
"White"
],
"images": [
"305009_nyhpyt.jpg"
]
},
{
"code": "305008",
"name": "Cotton fitted sheet pink",
"category": "bedroom",
"subcategory": "Sheets",
"tag": "Soft 100% cotton fitted sheet",
"description": "Cotton fitted sheet made of 100% high-quality cotton with a strong elastic edge. Suits higher mattresses (up to 14.5 cm) and retains shape after washing.",
"materials": [
"100% Cotton"
],
"dims": "60 × 120 cm",
"ages": "",
"certs": [],
"colors": [
"Pink"
],
"images": [
"305008_al4tvm.jpg"
]
},
{
"code": "305007",
"name": "Cotton fitted sheet grey",
"category": "bedroom",
"subcategory": "Sheets",
"tag": "Soft 100% cotton fitted sheet",
"description": "Cotton fitted sheet made of 100% high-quality cotton with a strong elastic edge. Suits higher mattresses (up to 14.5 cm) and retains shape after washing.",
"materials": [
"100% Cotton"
],
"dims": "60 × 120 cm",
"ages": "",
"certs": [],
"colors": [
"Grey"
],
"images": [
"305007_iu0krd.jpg"
]
},
{
"code": "304316",
"name": "B-Sensible 2-in-1 sheet & protector",
"category": "bedroom",
"subcategory": "Sheets",
"tag": "Waterproof, breathable 2-in-1 fitted sheet & mattress protector",
"description": "Waterproof and breathable B-Sensible 2-in-1 fitted sheet that doubles as a mattress protector. Uses DERMOFRESH technology — the natural fibre TENCEL, SMARTCEL sensitive, and an innovative polyurethane membrane that acts like a second skin. Inhibits bacterial growth naturally; breathable, anti-dust mites and waterproof.",
"materials": [
"100% Cotton",
"TENCEL",
"SMARTCEL sensitive",
"Polyurethane membrane"
],
"dims": "60 × 120 cm",
"ages": "",
"certs": [],
"colors": [
"Arran"
],
"images": [
"304316_nrigun.jpg"
]
},
{
"code": "304318",
"name": "B-Sensible 2-in-1 sheet & protector",
"category": "bedroom",
"subcategory": "Sheets",
"tag": "Waterproof, breathable 2-in-1 fitted sheet & mattress protector",
"description": "Waterproof and breathable B-Sensible 2-in-1 fitted sheet that doubles as a mattress protector. Uses DERMOFRESH technology — TENCEL, SMARTCEL sensitive, and an innovative polyurethane membrane that acts like a second skin. Inhibits bacterial growth naturally; breathable, anti-dust mites and waterproof.",
"materials": [
"100% Cotton",
"TENCEL",
"SMARTCEL sensitive",
"Polyurethane membrane"
],
"dims": "70 × 140 cm",
"ages": "",
"certs": [],
"colors": [
"Arran"
],
"images": [
"304318_htd8tn.jpg"
]
},
{
"code": "303828",
"name": "BEDDY bedding set mint",
"category": "bedroom",
"subcategory": "Bedding",
"tag": "100% cotton bedding set with playful tiny friends print",
"description": "Cotton bedding set including a duvet cover and pillowcase. Natural and breathable cotton — the best choice for your baby. The set is packed in a small tote bag that matches the bedding and can be used for various practical purposes.",
"materials": [
"100% Cotton"
],
"dims": "Duvet cover 100 × 130 cm; Pillowcase 60 × 40 cm",
"ages": "",
"certs": [],
"colors": [
"Mint"
],
"images": [
"303828_1_juynqq.jpg",
"303828_xkstvo.jpg"
]
},
{
"code": "303829",
"name": "BEDDY bedding set white",
"category": "bedroom",
"subcategory": "Bedding",
"tag": "100% cotton bedding set with playful tiny friends print",
"description": "Cotton bedding set including a duvet cover and pillowcase. Natural and breathable cotton — the best choice for your baby. The set is packed in a small tote bag that matches the bedding and can be used for various practical purposes.",
"materials": [
"100% Cotton"
],
"dims": "Duvet cover 100 × 130 cm; Pillowcase 60 × 40 cm",
"ages": "",
"certs": [],
"colors": [
"White"
],
"images": [
"303829_1_zj8ynr.jpg",
"303829_1_zj8ynr.jpg"
]
},
{
"code": "303538",
"name": "BUMBLE cot bumper",
"category": "bedroom",
"subcategory": "Cot bumpers",
"tag": "Soft 100% cotton cot bumper that wraps all sides",
"description": "The cot bumper covers all sides of the bed, creating a comfortable and safe environment by covering the bed rails. Breathable and soft against the skin, with two rows of binding cords for flexible and secure fastening. Outside is 100% natural cotton fabric. Machine washable.",
"materials": [
"100% Cotton shell",
"100% PES filling"
],
"dims": "360 × 30 cm",
"ages": "",
"certs": [],
"colors": [
"Beige"
],
"images": [
"303538_exkicg.jpg"
]
},
{
"code": "304102",
"name": "SLIIBA sleeping bag mint",
"category": "bedroom",
"subcategory": "Sleeping bags",
"tag": "2.0 TOG cotton sleeping bag for cosy autumn-winter nights",
"description": "The 2.0 TOG sleeping bag with double-layer cotton fabric and filling is ideal for the autumn-winter season. The side-to-bottom zip allows for easy dressing. A safer alternative to traditional blankets.",
"materials": [
"100% Cotton",
"100% PES filling"
],
"dims": "Length 80 cm",
"ages": "",
"certs": [],
"colors": [
"Mint"
],
"images": [
"304102_jikbll.jpg"
]
},
{
"code": "304103",
"name": "SLIIBA sleeping bag beige",
"category": "bedroom",
"subcategory": "Sleeping bags",
"tag": "2.0 TOG cotton sleeping bag for cosy autumn-winter nights",
"description": "The 2.0 TOG sleeping bag with double-layer cotton fabric and filling is ideal for the autumn-winter season. The side-to-bottom zip allows for easy dressing. A safer alternative to traditional blankets.",
"materials": [
"100% Cotton",
"100% PES filling"
],
"dims": "Length 80 cm",
"ages": "",
"certs": [],
"colors": [
"Beige"
],
"images": [
"304103_dkaajo.jpg"
]
},
{
"code": "303532",
"name": "SANDY muslin blanket mint",
"category": "bedroom",
"subcategory": "Blankets, swaddles & burp cloths",
"tag": "Extra-soft 4-layer cotton muslin blanket",
"description": "This soft blanket is made of cotton muslin fabric — warming yet airy. It can be used as a diaper, light blanket, changing cloth, bed sheet or towel. Especially good as a shade during breastfeeding or as a shoulder cover. Becomes even softer with every wash.",
"materials": [
"100% Cotton"
],
"dims": "80 × 100 cm",
"ages": "",
"certs": [],
"colors": [
"Mint"
],
"images": [
"303532_u1kbjt.jpg"
]
},
{
"code": "303531",
"name": "SANDY muslin blanket beige",
"category": "bedroom",
"subcategory": "Blankets, swaddles & burp cloths",
"tag": "Extra-soft 4-layer cotton muslin blanket",
"description": "This soft blanket is made of cotton muslin fabric — warming yet airy. It can be used as a diaper, light blanket, changing cloth, bed sheet or towel. Especially good as a shade during breastfeeding or as a shoulder cover. Becomes even softer with every wash.",
"materials": [
"100% Cotton"
],
"dims": "80 × 100 cm",
"ages": "",
"certs": [],
"colors": [
"Beige"
],
"images": [
"303531_xru24n.jpg"
]
},
{
"code": "303535",
"name": "SWATRY swaddle set mint/white",
"category": "bedroom",
"subcategory": "Blankets, swaddles & burp cloths",
"tag": "Multifunctional 2-pack cotton muslin swaddle set",
"description": "Muslin cloths are airy and multifunctional — use as a swaddle, breastfeeding cover or stroller cover. Soft against the skin and softer with every wash. Long-lasting; a beautiful welcome gift. Set of 2 pieces.",
"materials": [
"100% Cotton"
],
"dims": "70 × 70 cm",
"ages": "",
"certs": [],
"colors": [
"Mint",
"White"
],
"images": [
"303535_ylsgug.jpg"
]
},
{
"code": "303536",
"name": "SWATRY swaddle set pink/white",
"category": "bedroom",
"subcategory": "Blankets, swaddles & burp cloths",
"tag": "Multifunctional 2-pack cotton muslin swaddle set",
"description": "Muslin cloths are airy and multifunctional — use as a swaddle, breastfeeding cover or stroller cover. Soft against the skin and softer with every wash. Long-lasting; a beautiful welcome gift. Set of 2 pieces.",
"materials": [
"100% Cotton"
],
"dims": "70 × 70 cm",
"ages": "",
"certs": [],
"colors": [
"Pink",
"White"
],
"images": [
"303536_iuxhnn.jpg"
]
},
{
"code": "303533",
"name": "BURRY burp cloths mint",
"category": "bedroom",
"subcategory": "Blankets, swaddles & burp cloths",
"tag": "Soft 3-pack pastel muslin burp cloths",
"description": "A set of burp cloths in pastel colours (3 pcs). Muslin becomes even softer when washed and is comfortable, breathable and practical. Perfect for wiping mouths after a feed or as a base when changing nappies.",
"materials": [
"100% Cotton"
],
"dims": "50 × 50 cm",
"ages": "",
"certs": [],
"colors": [
"Mint",
"Beige",
"White"
],
"images": [
"303533_lf3vi9.jpg"
]
},
{
"code": "303534",
"name": "BURRY burp cloths beige",
"category": "bedroom",
"subcategory": "Blankets, swaddles & burp cloths",
"tag": "Soft 3-pack pastel muslin burp cloths",
"description": "A set of burp cloths in pastel colours (3 pcs). Muslin becomes even softer when washed and is comfortable, breathable and practical. Perfect for wiping mouths after a feed or as a base when changing nappies.",
"materials": [
"100% Cotton"
],
"dims": "50 × 50 cm",
"ages": "",
"certs": [],
"colors": [
"Beige",
"White",
"Pink"
],
"images": [
"303534_fh8cyd.jpg"
]
},
{
"code": "304055",
"name": "ALEXIS sleepsuit",
"category": "clothing",
"subcategory": "Newborn collection",
"tag": "Two-way zip footed sleepsuit for easy dressing",
"description": "A footed sleepsuit in soft bamboo-cotton interlock that breathes and feels gentle against baby's skin. Two-way zipper makes nappy changes effortless; footed hems and reversible sleeve ends extend its comfortable wear.",
"materials": [
"70% Bamboo",
"30% Cotton interlock"
],
"dims": "Sizes 44–62",
"ages": "Newborn",
"certs": [],
"colors": [
"White",
"Beige"
],
"images": [
"304055_b0sg1z.jpg"
]
},
{
"code": "304063",
"name": "KIM wrap-body",
"category": "clothing",
"subcategory": "Newborn collection",
"tag": "Soft bamboo wrap-body for sensitive newborn skin",
"description": "A soft and breathable wrap-body crafted from bamboo-cotton interlock that feels gentle against delicate newborn skin. Reversible sleeve ends and an extendable size for longer wear.",
"materials": [
"70% Bamboo",
"30% Cotton interlock"
],
"dims": "Sizes 44–62",
"ages": "Newborn",
"certs": [],
"colors": [
"White",
"Beige"
],
"images": [
"304063_sxdob7.jpg"
]
},
{
"code": "304071",
"name": "SATSIKE wrap-body",
"category": "clothing",
"subcategory": "Newborn collection",
"tag": "Frill-detail wrap-body in soft bamboo blend",
"description": "A wrap-body made from soft bamboo-cotton interlock that is breathable and pleasant on newborn skin. Cute frill detail, reversible sleeve ends and an extendable size for everyday comfort.",
"materials": [
"70% Bamboo",
"30% Cotton interlock"
],
"dims": "Sizes 44–62",
"ages": "Newborn",
"certs": [],
"colors": [
"White"
],
"images": [
"304071_freuww.jpg"
]
},
{
"code": "304075",
"name": "KIMMY wrap-body",
"category": "clothing",
"subcategory": "Newborn collection",
"tag": "Outside-seam wrap-body for ultimate baby comfort",
"description": "Designed with seams on the outside for total comfort against baby's skin. Made from soft, breathable bamboo-cotton interlock with reversible sleeve ends and an extendable size for growing newborns.",
"materials": [
"70% Bamboo",
"30% Cotton interlock"
],
"dims": "Sizes 44–62",
"ages": "Newborn",
"certs": [],
"colors": [
"White"
],
"images": [
"304075_cgsapc.jpg"
]
},
{
"code": "304079",
"name": "JAYME footed pants",
"category": "clothing",
"subcategory": "Newborn collection",
"tag": "Cosy footed pants in breathable bamboo blend",
"description": "Footed pants made from soft bamboo-cotton interlock that is breathable and pleasant on the skin. The footed hems keep little toes warm and comfortable.",
"materials": [
"70% Bamboo",
"30% Cotton interlock"
],
"dims": "Sizes 44–62",
"ages": "Newborn",
"certs": [],
"colors": [
"White",
"Beige"
],
"images": [
"304079_ljurqd.jpg"
]
},
{
"code": "304088",
"name": "JUDE bonnet",
"category": "clothing",
"subcategory": "Newborn collection",
"tag": "Tie-fastening bamboo bonnet for newborns",
"description": "A soft bamboo-cotton bonnet with a sweet tie fastening for a secure fit. Breathable and gentle against baby's skin, ideal for everyday wear.",
"materials": [
"70% Bamboo",
"30% Cotton interlock"
],
"dims": "Sizes 32–36 / 36–40 / 40–44",
"ages": "Newborn",
"certs": [],
"colors": [
"White",
"Beige"
],
"images": [
"304088_vyaap5.jpg"
]
},
{
"code": "304091",
"name": "JUDE bonnet white",
"category": "clothing",
"subcategory": "Newborn collection",
"tag": "Tie-fastening bamboo bonnet for newborns",
"description": "A soft bamboo-cotton bonnet with a sweet tie fastening for a secure fit. Breathable and gentle against baby's skin, ideal for everyday wear.",
"materials": [
"70% Bamboo",
"30% Cotton interlock"
],
"dims": "Sizes 32–36 / 36–40 / 40–44",
"ages": "Newborn",
"certs": [],
"colors": [
"White"
],
"images": [
"304091_hsi082.jpg"
]
},
{
"code": "304094",
"name": "KNOTTY knot hat",
"category": "clothing",
"subcategory": "Newborn collection",
"tag": "Adjustable knot-detail hat in soft bamboo",
"description": "A newborn knot hat made from breathable bamboo-cotton interlock that is gentle against the skin. The signature knot detail lets you adjust the size for a snug fit.",
"materials": [
"70% Bamboo",
"30% Cotton interlock"
],
"dims": "Size 36–40",
"ages": "Newborn",
"certs": [],
"colors": [
"White"
],
"images": [
"304094_xhcuuu.jpg"
]
},
{
"code": "304095",
"name": "JESSE mittens",
"category": "clothing",
"subcategory": "Newborn collection",
"tag": "Soft bamboo newborn mittens",
"description": "Lightweight newborn mittens made from soft, breathable bamboo-cotton interlock. Gentle on delicate skin and ideal for protecting tiny hands from scratches.",
"materials": [
"70% Bamboo",
"30% Cotton interlock"
],
"dims": "One size",
"ages": "Newborn",
"certs": [],
"colors": [
"White"
],
"images": [
"304095_lfdaoa.jpg"
]
},
{
"code": "304096",
"name": "ROBBIE booties",
"category": "clothing",
"subcategory": "Newborn collection",
"tag": "Cosy bamboo booties for newborns",
"description": "Soft newborn booties in breathable bamboo-cotton interlock. Extra gentle and pleasant against baby's skin to keep little feet warm and comfortable.",
"materials": [
"70% Bamboo",
"30% Cotton interlock"
],
"dims": "One size",
"ages": "Newborn",
"certs": [],
"colors": [
"White"
],
"images": [
"304096_smcaom.jpg"
]
},
{
"code": "306332",
"name": "BRIAN merino beanie beige",
"category": "clothing",
"subcategory": "Hats, mittens, socks & scarfs",
"tag": "100% merino beanie with year-round comfort",
"description": "A pure merino wool beanie that insulates in winter and helps regulate temperature in summer. Soft against baby skin, with anti-static and moisture-regulating properties.",
"materials": [
"100% Merino wool"
],
"dims": "Sizes 36–40 / 40–44",
"ages": "Baby",
"certs": [],
"colors": [
"Beige"
],
"images": [
"306332_nlnofz.jpg"
]
},
{
"code": "306330",
"name": "BRIAN merino beanie pink",
"category": "clothing",
"subcategory": "Hats, mittens, socks & scarfs",
"tag": "100% merino beanie with year-round comfort",
"description": "A pure merino wool beanie that insulates in winter and helps regulate temperature in summer. Soft against baby skin, with anti-static and moisture-regulating properties.",
"materials": [
"100% Merino wool"
],
"dims": "Sizes 36–40 / 40–44",
"ages": "Baby",
"certs": [],
"colors": [
"Pink"
],
"images": [
"306330_dcchis.jpg"
]
},
{
"code": "306334",
"name": "BRIAN merino beanie green",
"category": "clothing",
"subcategory": "Hats, mittens, socks & scarfs",
"tag": "100% merino beanie with year-round comfort",
"description": "A pure merino wool beanie that insulates in winter and helps regulate temperature in summer. Soft against baby skin, with anti-static and moisture-regulating properties.",
"materials": [
"100% Merino wool"
],
"dims": "Sizes 36–40 / 40–44",
"ages": "Baby",
"certs": [],
"colors": [
"Green"
],
"images": [
"306334_nrsstn.jpg"
]
},
{
"code": "306336",
"name": "BRIAN merino beanie dark blue",
"category": "clothing",
"subcategory": "Hats, mittens, socks & scarfs",
"tag": "100% merino beanie with year-round comfort",
"description": "A pure merino wool beanie that insulates in winter and helps regulate temperature in summer. Soft against baby skin, with anti-static and moisture-regulating properties.",
"materials": [
"100% Merino wool"
],
"dims": "Sizes 36–40 / 40–44",
"ages": "Baby",
"certs": [],
"colors": [
"Dark blue"
],
"images": [
"306336_sgbgqj.jpg"
]
},
{
"code": "306341",
"name": "BREMY bamboo hat dune",
"category": "clothing",
"subcategory": "Hats, mittens, socks & scarfs",
"tag": "100% bamboo knitted hat with cute ear details",
"description": "A soft 100% bamboo knitted hat with playful ear details. Naturally breathable, hypoallergenic and antibacterial.",
"materials": [
"100% Bamboo"
],
"dims": "Size 36–40",
"ages": "Baby",
"certs": [],
"colors": [
"Dune"
],
"images": [
"306341_lqabrs.jpg"
]
},
{
"code": "306338",
"name": "BREMY bamboo hat peony",
"category": "clothing",
"subcategory": "Hats, mittens, socks & scarfs",
"tag": "100% bamboo knitted hat with cute ear details",
"description": "A soft 100% bamboo knitted hat with playful ear details. Naturally breathable, hypoallergenic and antibacterial.",
"materials": [
"100% Bamboo"
],
"dims": "Size 36–40",
"ages": "Baby",
"certs": [],
"colors": [
"Peony"
],
"images": [
"306338_e43mdf.jpg"
]
},
{
"code": "306339",
"name": "BREMY bamboo hat natural white",
"category": "clothing",
"subcategory": "Hats, mittens, socks & scarfs",
"tag": "100% bamboo knitted hat with cute ear details",
"description": "A soft 100% bamboo knitted hat with playful ear details. Naturally breathable, hypoallergenic and antibacterial.",
"materials": [
"100% Bamboo"
],
"dims": "Size 36–40",
"ages": "Baby",
"certs": [],
"colors": [
"Natural white"
],
"images": [
"306339_mhkseb.jpg"
]
},
{
"code": "306340",
"name": "BREMY bamboo hat foggy grey",
"category": "clothing",
"subcategory": "Hats, mittens, socks & scarfs",
"tag": "100% bamboo knitted hat with cute ear details",
"description": "A soft 100% bamboo knitted hat with playful ear details. Naturally breathable, hypoallergenic and antibacterial.",
"materials": [
"100% Bamboo"
],
"dims": "Size 36–40",
"ages": "Baby",
"certs": [],
"colors": [
"Foggy grey"
],
"images": [
"306340_fk15nr.jpg"
]
},
{
"code": "306329",
"name": "BEKA merino hat",
"category": "clothing",
"subcategory": "Hats, mittens, socks & scarfs",
"tag": "Soft merino knitted hat for year-round wear",
"description": "A pure merino wool knitted hat that insulates in winter and helps regulate temperature in summer. Soft against baby skin, naturally moisture-regulating and anti-static.",
"materials": [
"100% Merino wool"
],
"dims": "Size 36–40",
"ages": "Baby",
"certs": [],
"colors": [
"White",
"Beige"
],
"images": [
"306329_taiatz.jpg"
]
},
{
"code": "306358",
"name": "RITEN ribbed mittens beige",
"category": "clothing",
"subcategory": "Hats, mittens, socks & scarfs",
"tag": "Ribbed merino mittens for warm little hands",
"description": "Soft ribbed mittens knitted from 100% merino wool. Keep tiny hands warm in winter and comfortably cool in summer.",
"materials": [
"100% Merino wool"
],
"dims": "0–12 months",
"ages": "0–12 months",
"certs": [],
"colors": [
"Beige"
],
"images": [
"306358_cmxyyk.jpg"
]
},
{
"code": "306357",
"name": "RITEN ribbed mittens pink",
"category": "clothing",
"subcategory": "Hats, mittens, socks & scarfs",
"tag": "Ribbed merino mittens for warm little hands",
"description": "Soft ribbed mittens knitted from 100% merino wool. Keep tiny hands warm in winter and comfortably cool in summer.",
"materials": [
"100% Merino wool"
],
"dims": "0–12 months",
"ages": "0–12 months",
"certs": [],
"colors": [
"Pink"
],
"images": [
"306357_hzuyku.jpg"
]
},
{
"code": "306359",
"name": "RITEN ribbed mittens green",
"category": "clothing",
"subcategory": "Hats, mittens, socks & scarfs",
"tag": "Ribbed merino mittens for warm little hands",
"description": "Soft ribbed mittens knitted from 100% merino wool. Keep tiny hands warm in winter and comfortably cool in summer.",
"materials": [
"100% Merino wool"
],
"dims": "0–12 months",
"ages": "0–12 months",
"certs": [],
"colors": [
"Green"
],
"images": [
"306359_f7suxk.jpg"
]
},
{
"code": "306360",
"name": "RITEN ribbed mittens dark blue",
"category": "clothing",
"subcategory": "Hats, mittens, socks & scarfs",
"tag": "Ribbed merino mittens for warm little hands",
"description": "Soft ribbed mittens knitted from 100% merino wool. Keep tiny hands warm in winter and comfortably cool in summer.",
"materials": [
"100% Merino wool"
],
"dims": "0–12 months",
"ages": "0–12 months",
"certs": [],
"colors": [
"Dark blue"
],
"images": [
"306360_ghkx3k.jpg"
]
},
{
"code": "306342",
"name": "RITA mittens",
"category": "clothing",
"subcategory": "Hats, mittens, socks & scarfs",
"tag": "One-size merino mittens for cosy comfort",
"description": "One-size ribbed mittens crafted from 100% merino wool. Keep little hands warm in winter and pleasantly cool in summer.",
"materials": [
"100% Merino wool"
],
"dims": "One size",
"ages": "Baby",
"certs": [],
"colors": [
"White"
],
"images": [
"306342_hic4rs.jpg"
]
},
{
"code": "306344",
"name": "SKROL rollneck scarf beige",
"category": "clothing",
"subcategory": "Hats, mittens, socks & scarfs",
"tag": "Easy-fit merino rollneck scarf for little ones",
"description": "A soft merino wool rollneck scarf that slips on with ease. Naturally insulating, anti-static and moisture-regulating.",
"materials": [
"100% Merino wool"
],
"dims": "One size",
"ages": "Baby",
"certs": [],
"colors": [
"Beige"
],
"images": [
"306344_liroeq.jpg"
]
},
{
"code": "306343",
"name": "SKROL rollneck scarf pink",
"category": "clothing",
"subcategory": "Hats, mittens, socks & scarfs",
"tag": "Easy-fit merino rollneck scarf for little ones",
"description": "A soft merino wool rollneck scarf that slips on with ease. Naturally insulating, anti-static and moisture-regulating.",
"materials": [
"100% Merino wool"
],
"dims": "One size",
"ages": "Baby",
"certs": [],
"colors": [
"Pink"
],
"images": [
"306343_fizfhz.jpg"
]
},
{
"code": "306345",
"name": "SKROL rollneck scarf green",
"category": "clothing",
"subcategory": "Hats, mittens, socks & scarfs",
"tag": "Easy-fit merino rollneck scarf for little ones",
"description": "A soft merino wool rollneck scarf that slips on with ease. Naturally insulating, anti-static and moisture-regulating.",
"materials": [
"100% Merino wool"
],
"dims": "One size",
"ages": "Baby",
"certs": [],
"colors": [
"Green"
],
"images": [
"306345_ejbrsv.jpg"
]
},
{
"code": "306346",
"name": "SKROL rollneck scarf dark blue",
"category": "clothing",
"subcategory": "Hats, mittens, socks & scarfs",
"tag": "Easy-fit merino rollneck scarf for little ones",
"description": "A soft merino wool rollneck scarf that slips on with ease. Naturally insulating, anti-static and moisture-regulating.",
"materials": [
"100% Merino wool"
],
"dims": "One size",
"ages": "Baby",
"certs": [],
"colors": [
"Dark blue"
],
"images": [
"306346_hvrvbg.jpg"
]
},
{
"code": "306349",
"name": "SOKI merino socks beige",
"category": "clothing",
"subcategory": "Hats, mittens, socks & scarfs",
"tag": "Pure merino baby socks for sensitive skin",
"description": "Soft 100% merino wool socks designed to keep little feet warm in winter and cool in summer. Naturally moisture-regulating and anti-static.",
"materials": [
"100% Merino wool"
],
"dims": "0–3 / 3–6 months",
"ages": "0–6 months",
"certs": [],
"colors": [
"Beige"
],
"images": [
"306349_kq94lf.jpg"
]
},
{
"code": "306347",
"name": "SOKI merino socks pink",
"category": "clothing",
"subcategory": "Hats, mittens, socks & scarfs",
"tag": "Pure merino baby socks for sensitive skin",
"description": "Soft 100% merino wool socks designed to keep little feet warm in winter and cool in summer.",
"materials": [
"100% Merino wool"
],
"dims": "0–3 / 3–6 months",
"ages": "0–6 months",
"certs": [],
"colors": [
"Pink"
],
"images": [
"306347_t8ebnk.jpg"
]
},
{
"code": "306351",
"name": "SOKI merino socks green",
"category": "clothing",
"subcategory": "Hats, mittens, socks & scarfs",
"tag": "Pure merino baby socks for sensitive skin",
"description": "Soft 100% merino wool socks designed to keep little feet warm in winter and cool in summer.",
"materials": [
"100% Merino wool"
],
"dims": "0–3 / 3–6 months",
"ages": "0–6 months",
"certs": [],
"colors": [
"Green"
],
"images": [
"306351_ebhjz8.jpg"
]
},
{
"code": "306353",
"name": "SOKI merino socks dark blue",
"category": "clothing",
"subcategory": "Hats, mittens, socks & scarfs",
"tag": "Pure merino baby socks for sensitive skin",
"description": "Soft 100% merino wool socks designed to keep little feet warm in winter and cool in summer.",
"materials": [
"100% Merino wool"
],
"dims": "0–3 / 3–6 months",
"ages": "0–6 months",
"certs": [],
"colors": [
"Dark blue"
],
"images": [
"306353_jtxsyh.jpg"
]
},
{
"code": "306355",
"name": "SOKI merino socks natural white",
"category": "clothing",
"subcategory": "Hats, mittens, socks & scarfs",
"tag": "Pure merino baby socks for sensitive skin",
"description": "Soft 100% merino wool socks designed to keep little feet warm in winter and cool in summer.",
"materials": [
"100% Merino wool"
],
"dims": "0–3 / 3–6 months",
"ages": "0–6 months",
"certs": [],
"colors": [
"Natural white"
],
"images": [
"306355_yjahwb.jpg"
]
},
{
"code": "306361",
"name": "PAPSU knitted booties white",
"category": "clothing",
"subcategory": "Hats, mittens, socks & scarfs",
"tag": "Cosy merino knitted booties for newborns",
"description": "Soft knitted booties made from 100% merino wool. Keep tiny feet warm in winter and cool in summer.",
"materials": [
"100% Merino wool"
],
"dims": "0–3 months",
"ages": "0–3 months",
"certs": [],
"colors": [
"White"
],
"images": [
"306361_eawayj.jpg"
]
},
{
"code": "306362",
"name": "PAPSU knitted booties pink",
"category": "clothing",
"subcategory": "Hats, mittens, socks & scarfs",
"tag": "Cosy merino knitted booties for newborns",
"description": "Soft knitted booties made from 100% merino wool. Keep tiny feet warm in winter and cool in summer.",
"materials": [
"100% Merino wool"
],
"dims": "0–3 months",
"ages": "0–3 months",
"certs": [],
"colors": [
"Pink"
],
"images": [
"306362_qe95r0.jpg"
]
},
{
"code": "306363",
"name": "PAPSU knitted booties green",
"category": "clothing",
"subcategory": "Hats, mittens, socks & scarfs",
"tag": "Cosy merino knitted booties for newborns",
"description": "Soft knitted booties made from 100% merino wool. Keep tiny feet warm in winter and cool in summer.",
"materials": [
"100% Merino wool"
],
"dims": "0–3 months",
"ages": "0–3 months",
"certs": [],
"colors": [
"Green"
],
"images": [
"306363_asb4my.jpg"
]
},
{
"code": "306349",
"name": "PAPSU knitted booties beige",
"category": "clothing",
"subcategory": "Hats, mittens, socks & scarfs",
"tag": "Cosy merino knitted booties for newborns",
"description": "Soft knitted booties made from 100% merino wool. Keep tiny feet warm in winter and cool in summer.",
"materials": [
"100% Merino wool"
],
"dims": "0–3 months",
"ages": "0–3 months",
"certs": [],
"colors": [
"Beige"
],
"images": [
"306349_kq94lf.jpg"
]
},
{
"code": "306378",
"name": "MERIITA merino blanket pink",
"category": "clothing",
"subcategory": "Knitted blankets",
"tag": "Lightweight merino blanket for year-round use",
"description": "A 100% merino wool blanket that is lightweight, naturally breathable and keeps its shape. Does not itch, smell or crease — keeps baby warm in winter and cool in summer.",
"materials": [
"100% Merino wool"
],
"dims": "80 × 100 cm",
"ages": "Baby",
"certs": [],
"colors": [
"Pink"
],
"images": [
"306378_vjtdbf.jpg"
]
},
{
"code": "306379",
"name": "MERIITA merino blanket green",
"category": "clothing",
"subcategory": "Knitted blankets",
"tag": "Lightweight merino blanket for year-round use",
"description": "A 100% merino wool blanket that is lightweight, naturally breathable and keeps its shape. Does not itch, smell or crease — keeps baby warm in winter and cool in summer.",
"materials": [
"100% Merino wool"
],
"dims": "80 × 100 cm",
"ages": "Baby",
"certs": [],
"colors": [
"Green"
],
"images": [
"306379_ietbjm.jpg"
]
},
{
"code": "304098",
"name": "DOTSI cotton blanket",
"category": "clothing",
"subcategory": "Knitted blankets",
"tag": "Breathable 100% cotton blanket for everyday use",
"description": "A naturally breathable cotton blanket that is lightweight and keeps its shape over time. Anti-static and moisture-regulating, comfortable year-round.",
"materials": [
"100% Cotton"
],
"dims": "75 × 100 cm",
"ages": "Baby",
"certs": [],
"colors": [
"Natural white"
],
"images": [
"304098_h8qolb.jpg"
]
},
{
"code": "306383",
"name": "MERCI merino overall pink",
"category": "clothing",
"subcategory": "Knitted overall",
"tag": "Luxuriously soft merino overall for cosy days",
"description": "Wrap your newborn in a luxurious merino wool overall combining unparalleled softness with natural warmth. Long zipper and extended ribs on sleeves and legs make dressing easy and extend the wearing time.",
"materials": [
"100% Merino wool"
],
"dims": "Sizes 56–62 / 68–74 / 80–86",
"ages": "Newborn–12 months",
"certs": [],
"colors": [
"Pink"
],
"images": [
"306383_xzpmjn.jpg"
]
},
{
"code": "306380",
"name": "MERCI merino overall green",
"category": "clothing",
"subcategory": "Knitted overall",
"tag": "Luxuriously soft merino overall for cosy days",
"description": "Wrap your newborn in a luxurious merino wool overall combining unparalleled softness with natural warmth. Long zipper and extended ribs on sleeves and legs make dressing easy and extend the wearing time.",
"materials": [
"100% Merino wool"
],
"dims": "Sizes 56–62 / 68–74 / 80–86",
"ages": "Newborn–12 months",
"certs": [],
"colors": [
"Green"
],
"images": [
"306380_y92ct1.jpg"
]
},
{
"code": "299336",
"name": "Car window roller-shade",
"category": "car",
"subcategory": "Sun shade",
"tag": "Retractable roller sunshade with one-press rewind",
"description": "Stay cool and protected with the Tinynord car window roller-shade. Easy to install with strong suction cups and a one-press rewind button. Blocks harmful UV rays, reduces glare and lowers interior temperature. 2-pack.",
"materials": [],
"dims": "40 × 50 cm",
"ages": "",
"certs": [
"50+ UPF"
],
"colors": [
"Black"
],
"images": [
"299336_2_c1ykxh.jpg",
"299336_3_motrad.jpg",
"299336_4_hnqh5l.jpg",
"299336_5_efjudf.jpg",
"299336_6_zpw14q.jpg",
"299336_7_elgsid.jpg",
"299336_4_hnqh5l.jpg"
]
},
{
"code": "299334",
"name": "Car trash box",
"category": "car",
"subcategory": "Car trash box",
"tag": "Compact leakproof trash box with mesh side pockets",
"description": "Keep your car clean and clutter-free with this compact, leakproof trash box. Water-resistant vinyl lining and side mesh pockets. Easy to mount anywhere in your vehicle and simple to empty.",
"materials": [
"Water-resistant vinyl"
],
"dims": "25 × 16 × 15 cm",
"ages": "",
"certs": [
"Waterproof"
],
"colors": [
"Black"
],
"images": [
"299334_1_hqbglj.jpg",
"299334_2_qs6y37.jpg",
"299334_3_ksgkgl.jpg",
"299334_4_djiwjb.jpg",
"299334_5_mbf2fz.jpg",
"299334_6_geq8yt.jpg",
"299334_7_q9kbma.jpg",
"299334_3_ksgkgl.jpg"
]
},
{
"code": "299348",
"name": "Car seat protector high-back",
"category": "car",
"subcategory": "Car seat protector",
"tag": "Universal high-back protector with storage pockets",
"description": "Universal car seat protector with high back cover. Placed under a kids car seat or baby carrier. Storage pockets for smaller items. Waterproof, stain resistant, with a non-slip base.",
"materials": [],
"dims": "45 × 120 cm",
"ages": "",
"certs": [
"Waterproof",
"BPA free"
],
"colors": [
"Black"
],
"images": [
"299348_w4olyb.jpg"
]
},
{
"code": "299347",
"name": "Kick mat",
"category": "car",
"subcategory": "Kick mat",
"tag": "Universal back-of-seat protector with pockets",
"description": "Universal protection for the rear side of the car seat. Protects the front seats from kicking and dirt. Storage pockets, easy to adjust with buckle, waterproof and stain resistant.",
"materials": [],
"dims": "45 × 61 cm",
"ages": "",
"certs": [
"Waterproof",
"BPA free"
],
"colors": [
"Black"
],
"images": [
"299347_cedzfi.jpg"
]
},
{
"code": "299335",
"name": "Car back seat organiser",
"category": "car",
"subcategory": "Back seat organiser",
"tag": "Universal backseat organiser with multiple pockets",
"description": "Universal car backseat organiser with tablet holder. Protects the front seats from kicking and dirt. Multiple storage pockets. Easy to adjust with buckle, waterproof and stain resistant.",
"materials": [],
"dims": "43 × 59 cm",
"ages": "",
"certs": [
"Waterproof",
"BPA free"
],
"colors": [
"Grey"
],
"images": [
"299335_2_rb6i24.jpg",
"299335_3_ugnzow.jpg",
"299335_4_tiimkd.jpg",
"299335_5_hdaph5.jpg",
"299335_6_fettzp.jpg",
"299335_5_hdaph5.jpg"
]
},
{
"code": "car-mirror-led",
"name": "Car seat mirror with LED",
"category": "car",
"subcategory": "Car mirror",
"tag": "LED-lit back seat mirror with remote control",
"description": "Built-in LED backlighting in the mirror lets you see the baby clearly at any time. The included remote control lets you turn the lights on and off from the driver's seat. Pivoting base; fits most adjustable headrests.",
"materials": [],
"dims": "28 × 20 cm",
"ages": "",
"certs": [
"BPA free",
"Shatterproof"
],
"colors": [
"Black"
],
"images": [
"PRODUCT%20CATEGORIES/CAR%20ACCESSORIES/PRODUCT%20PICTURES/car_mirror3-01.jpg"
]
},
{
"code": "car-mirror-textile",
"name": "Back seat mirror, textile",
"category": "car",
"subcategory": "Car mirror",
"tag": "Soft textile-framed shatterproof mirror",
"description": "Back seat mirror for keeping visual contact with your baby while they are seated rear-facing. Safe, shatterproof. Adjustable straps attach easily and securely to the car seat headrest.",
"materials": [],
"dims": "22 × 32 cm",
"ages": "",
"certs": [
"Shatterproof"
],
"colors": [
"Black"
],
"images": [
"PRODUCT%20CATEGORIES/CAR%20ACCESSORIES/PRODUCT%20PICTURES/Car%20mirror2.jpg"
]
},
{
"code": "car-mirror-acrylic",
"name": "Back seat mirror, acrylic",
"category": "car",
"subcategory": "Car mirror",
"tag": "Shatterproof acrylic mirror with pivoting base",
"description": "A car seat mirror designed to give you visual contact with your rear-facing child. Safe, shatterproof, made of high-quality eco-friendly acrylic. Pivoting base.",
"materials": [
"Acrylic"
],
"dims": "22 × 32 cm",
"ages": "",
"certs": [
"Shatterproof"
],
"colors": [
"Black"
],
"images": [
"PRODUCT%20CATEGORIES/CAR%20ACCESSORIES/PRODUCT%20PICTURES/Car%20mirror1.jpg"
]
},
{
"code": "car-sunshade-2pcs",
"name": "Car sunshade (2 pcs)",
"category": "car",
"subcategory": "Sun shade",
"tag": "Elastic mesh window sunshade with 50+ UPF, 2-pack",
"description": "Made of elastic nylon mesh, this sunshade is designed to fit any car window. Suction cups ensure a secure and easy installation. 50+ UPF protection.",
"materials": [
"Elastic nylon mesh"
],
"dims": "36 × 43 cm",
"ages": "",
"certs": [
"50+ UPF"
],
"colors": [
"Black"
],
"images": [
"PRODUCT%20CATEGORIES/CAR%20ACCESSORIES/PRODUCT%20PICTURES/Sunshade.jpg"
]
},
{
"code": "car-low-back-protector",
"name": "Car seat protector, low-back",
"category": "car",
"subcategory": "Car seat protector",
"tag": "Universal low-back protector with storage pockets",
"description": "Universal car seat protector with low back cover. Storage pockets for smaller items. Waterproof, stain resistant, non-slip base.",
"materials": [],
"dims": "45 × 82 cm",
"ages": "",
"certs": [
"Waterproof",
"BPA free"
],
"colors": [
"Black"
],
"images": [
"PRODUCT%20CATEGORIES/CAR%20ACCESSORIES/PRODUCT%20PICTURES/Protector&Kickmat-02.jpg"
]
},
{
"code": "car-kickmat-tablet",
"name": "Kick mat with tablet holder",
"category": "car",
"subcategory": "Kick mat",
"tag": "Backseat organiser with built-in tablet holder",
"description": "Universal car backseat organiser with tablet holder. Storage pockets and tablet holder. Adjustable straps fit most car seats.",
"materials": [],
"dims": "43 × 53 cm (tablet holder 26 × 16 cm)",
"ages": "",
"certs": [
"Waterproof",
"BPA free"
],
"colors": [
"Black"
],
"images": [
"PRODUCT%20CATEGORIES/CAR%20ACCESSORIES/PRODUCT%20PICTURES/Protector&Kickmat-01.jpg"
]
},
{
"code": "car-3in1-protector",
"name": "3-in-1 car seat protector & kick mat",
"category": "car",
"subcategory": "Car seat protector",
"tag": "Multifunctional protector, kick mat and tablet holder",
"description": "The Universal 3-in-1 protector keeps your vehicle seats clean, organized and protected. Use it as a full seat protector with high back, a low-back protector, or a kick mat with built-in tablet holder. Shields seats from dirt, spills and scuff marks.",
"materials": [],
"dims": "49 × 118 cm (iPad holder max 26 × 19 cm)",
"ages": "",
"certs": [
"Waterproof",
"BPA free"
],
"colors": [],
"images": [
"301496_3_sb7bvl.jpg",
"9645_yqq224.jpg"
]
},
{
"code": "304339",
"name": "GIA safety gate black",
"category": "safety",
"subcategory": "Safety gates",
"tag": "Pressure-fit auto-close 2-way safety gate",
"description": "Indoor security gate suitable for bedrooms, kitchens, stairs and hallways. Fits openings 75–82 cm wide; for wider areas, extension parts are sold separately. Auto-close, 2-way opening, no drilling required.",
"materials": [
"Metal"
],
"dims": "82 × 4 × 77 cm (fits 75–82 cm)",
"ages": "",
"certs": [
"EN 1930:2011",
"EN 71"
],
"colors": [
"Black"
],
"images": [
"304339_1_ddzx4o.jpg"
]
},
{
"code": "304341",
"name": "GIA gate extension 7 cm",
"category": "safety",
"subcategory": "Safety gates",
"tag": "7 cm extension for GIA safety gate",
"description": "Safety Gate Extension (7 cm) widens the standard safety gate to fit larger or irregularly sized openings. Maximum of 2 extensions per gate (one on each side).",
"materials": [
"Metal"
],
"dims": "7 cm",
"ages": "",
"certs": [
"EN 1930:2011",
"EN 71"
],
"colors": [
"White",
"Black"
],
"images": [
"304341_1_jmd4sg.jpg",
"304341_2_jglfu3.jpg"
]
},
{
"code": "304343",
"name": "GIA gate extension 14 cm",
"category": "safety",
"subcategory": "Safety gates",
"tag": "14 cm extension for GIA safety gate",
"description": "Safety Gate Extension (14 cm) widens the standard safety gate to fit larger or irregularly sized openings. Maximum of 2 extensions per gate (one on each side).",
"materials": [
"Metal"
],
"dims": "14 cm",
"ages": "",
"certs": [
"EN 1930:2011",
"EN 71"
],
"colors": [
"White",
"Black"
],
"images": [
"304343_1_wvtpso.jpg",
"304343_2_mvks9r.jpg"
]
},
{
"code": "304345",
"name": "GIA gate extension 28 cm",
"category": "safety",
"subcategory": "Safety gates",
"tag": "28 cm extension for GIA safety gate",
"description": "Safety Gate Extension (28 cm) widens the standard safety gate to fit larger or irregularly sized openings. Maximum of 2 extensions per gate (one on each side).",
"materials": [
"Metal"
],
"dims": "28 cm",
"ages": "",
"certs": [
"EN 1930:2011",
"EN 71"
],
"colors": [
"White",
"Black"
],
"images": [
"304345_1_i4bdsv.jpg",
"304345_2_mgbowa.jpg"
]
},
{
"code": "301588",
"name": "GIA gate extension white",
"category": "safety",
"subcategory": "Safety gates",
"tag": "Extension piece for GIA safety gate",
"description": "Safety Gate Extension widens the standard safety gate to fit larger or irregularly sized openings.",
"materials": [
"Metal"
],
"dims": "",
"ages": "",
"certs": [
"EN 1930:2011",
"EN 71"
],
"colors": [
"White"
],
"images": [
"301588_vyvgic.jpg"
]
},
{
"code": "301595",
"name": "GIA gate extension black",
"category": "safety",
"subcategory": "Safety gates",
"tag": "Extension piece for GIA safety gate",
"description": "Safety Gate Extension widens the standard safety gate to fit larger or irregularly sized openings.",
"materials": [
"Metal"
],
"dims": "",
"ages": "",
"certs": [
"EN 1930:2011",
"EN 71"
],
"colors": [
"Black"
],
"images": [
"301595_edited2_itschp.jpg",
"301595_edited2_itschp.jpg"
]
},
{
"code": "301601",
"name": "GIA gate extension",
"category": "safety",
"subcategory": "Safety gates",
"tag": "Extension piece for GIA safety gate",
"description": "Safety Gate Extension widens the standard safety gate to fit larger or irregularly sized openings.",
"materials": [
"Metal"
],
"dims": "",
"ages": "",
"certs": [
"EN 1930:2011",
"EN 71"
],
"colors": [],
"images": [
"301601_edited2_qjd7fe.jpg",
"301601_edited2_qjd7fe.jpg"
]
},
{
"code": "301618",
"name": "GIA gate extension",
"category": "safety",
"subcategory": "Safety gates",
"tag": "Extension piece for GIA safety gate",
"description": "Safety Gate Extension widens the standard safety gate to fit larger or irregularly sized openings.",
"materials": [
"Metal"
],
"dims": "",
"ages": "",
"certs": [
"EN 1930:2011",
"EN 71"
],
"colors": [],
"images": [
"301618_edited2_lg5iou.jpg",
"301618_edited2_lg5iou.jpg"
]
},
{
"code": "306374",
"name": "HUFS stroller mittens black",
"category": "stroller-acc",
"subcategory": "Stroller mittens",
"tag": "Wind- and water-repellent fur-lined hand muffs",
"description": "Warm stroller mittens that prevent hands from freezing during a walk, even at low temperatures. Wind and water repellent with soft artificial fur lining. Velcro attaches to any stroller handle.",
"materials": [
"100% Polyester",
"100% Fur (lining)"
],
"dims": "30 × 17 cm",
"ages": "",
"certs": [
"OEKO-TEX 100"
],
"colors": [
"Black"
],
"images": [
"306374_2_d7sggb.jpg",
"306374_2_d7sggb.jpg"
]
},
{
"code": "306371",
"name": "MILO baby overall",
"category": "stroller-acc",
"subcategory": "Footmuffs",
"tag": "Hooded windproof newborn overall for first outdoor trips",
"description": "A hooded newborn overall for the first outdoor trips. Wind and rain resistant, ideal for winter use. Two front zippers provide space for dressing a child sleeping in either a stroller or a car seat. Inside has seat-belt holes for a 3-point harness.",
"materials": [
"100% Polyamide (main)",
"100% Cotton jersey (lining)"
],
"dims": "Length 80 cm",
"ages": "0–6 months",
"certs": [
"OEKO-TEX 100",
"Waterproof 5000 mm",
"Breathable 3000 g/m²/24h"
],
"colors": [
"Beige"
],
"images": [
"306371_1_jlxpig.jpg",
"306371_2_vu6gwi.jpg"
]
},
{
"code": "306369",
"name": "MAX footmuff black",
"category": "stroller-acc",
"subcategory": "Footmuffs",
"tag": "Extendable winter footmuff with detachable fur",
"description": "A footmuff designed for cold weather conditions. The outer shell protects against rain, snow and wind. Extendable from 90 to 105 cm. Universal back design fits most stroller models. 90% down / 10% feather filling, anti-slip back panel and a fully detachable fur strap. Comes with a compact carry bag.",
"materials": [
"100% Polyamide",
"Cotton jersey (lining)",
"Wool",
"Down",
"Feather"
],
"dims": "46 × 90 cm (extendable to 105 cm)",
"ages": "",
"certs": [
"OEKO-TEX 100",
"Waterproof 5000 mm",
"Breathable 3000 g/m²/24h"
],
"colors": [
"Black"
],
"images": [
"306369_1_hby1ak.jpg",
"306369_2_eyyuqu.jpg",
"306369_3_mm7m1i.jpg",
"306369_4_pwh2je.jpg",
"306369_5_ugbp8w.jpg"
]
},
{
"code": "299346",
"name": "Cup holder with screw",
"category": "stroller-acc",
"subcategory": "Cup holder",
"tag": "Universal screw-mount cup holder",
"description": "Universal cup holder with screw attachment for Tinynord and most strollers. The screw attachment system lets you place your drink bottle in the perfect position.",
"materials": [],
"dims": "15 × 10 cm",
"ages": "",
"certs": [],
"colors": [
"Black"
],
"images": [
"299346_vi31zm.jpg"
]
},
{
"code": "299331",
"name": "Stroller hooks (2 pcs)",
"category": "stroller-acc",
"subcategory": "Stroller hooks",
"tag": "Universal velcro stroller hooks, 2-pack",
"description": "Tinynord stroller hooks make every outing easier. Universal fit — secure with strong velcro straps and hang your diaper bag, shopping bags or backpack for hands-free convenience.",
"materials": [],
"dims": "",
"ages": "",
"certs": [],
"colors": [
"Black"
],
"images": [
"299331_2_fmai07.jpg",
"299331_brpq3x.jpg"
]
},
{
"code": "298915",
"name": "Nursing bag",
"category": "stroller-acc",
"subcategory": "Nursing bag",
"tag": "Stylish nursing bag that doubles as handbag",
"description": "A practical and stylish way to keep your essentials organised. Designed to look and function as a handbag, office or gym bag, attached to the stroller handle using included pram hooks. One large compartment with small inner pockets and a wide shoulder strap.",
"materials": [
"100% Polyester"
],
"dims": "42 × 36 × 12 cm",
"ages": "",
"certs": [],
"colors": [
"Caviar black"
],
"images": [
"298915_2_kgbti1.jpg",
"298915_2_kgbti1.jpg"
]
},
{
"code": "282547",
"name": "Stroller accessory",
"category": "stroller-acc",
"subcategory": "Accessories",
"tag": "Tinynord stroller accessory",
"description": "A practical accessory designed to fit Tinynord and most strollers from other manufacturers.",
"materials": [],
"dims": "",
"ages": "",
"certs": [],
"colors": [],
"images": [
"282547_oni76r.jpg"
]
},
{
"code": "282548",
"name": "Stroller accessory",
"category": "stroller-acc",
"subcategory": "Accessories",
"tag": "Tinynord stroller accessory",
"description": "A practical accessory designed to fit Tinynord and most strollers from other manufacturers.",
"materials": [],
"dims": "",
"ages": "",
"certs": [],
"colors": [],
"images": [
"282548_on0ilj.jpg"
]
},
{
"code": "293455",
"name": "Stroller accessory",
"category": "stroller-acc",
"subcategory": "Accessories",
"tag": "Tinynord stroller accessory",
"description": "A practical accessory designed to fit Tinynord and most strollers from other manufacturers.",
"materials": [],
"dims": "",
"ages": "",
"certs": [],
"colors": [],
"images": [
"293455_c66ztp.jpg"
]
},
{
"code": "293456",
"name": "Stroller accessory",
"category": "stroller-acc",
"subcategory": "Accessories",
"tag": "Tinynord stroller accessory",
"description": "A practical accessory designed to fit Tinynord and most strollers from other manufacturers.",
"materials": [],
"dims": "",
"ages": "",
"certs": [],
"colors": [],
"images": [
"293456_yh2gt9.jpg"
]
},
{
"code": "293457",
"name": "Stroller accessory",
"category": "stroller-acc",
"subcategory": "Accessories",
"tag": "Tinynord stroller accessory",
"description": "A practical accessory designed to fit Tinynord and most strollers from other manufacturers.",
"materials": [],
"dims": "",
"ages": "",
"certs": [],
"colors": [],
"images": [
"293457_ukcyx2.jpg"
]
},
{
"code": "256491",
"name": "Universal rain cover",
"category": "stroller-acc",
"subcategory": "Rain cover",
"tag": "Universal rain cover with integrated accessory bag",
"description": "Universal rain cover with integrated accessory bag. Fits Tinynord and most strollers. Velcro front opening for easy access. Use on both carrycot and seat unit. Waterproof, wind-resistant, with built-in mesh panels for fresh airflow.",
"materials": [],
"dims": "",
"ages": "",
"certs": [
"Waterproof"
],
"colors": [
"Transparent"
],
"images": [
"256491_1_f0wajb.jpg",
"256491_2_ugqxpa.jpg",
"256491_3_tsrzor.jpg"
]
},
{
"code": "active-comfort",
"name": "ACTIVE Stroller Set",
"category": "strollers",
"subcategory": "",
"tag": "Smooth, all-season rides for modern, active parents",
"description": "The Tinynord ACTIVE Stroller Set is a complete travel system that includes a carrycot, reversible seat unit and chassis, designed to suit the lifestyle of modern and active parents throughout all four seasons. An additional shock absorber system (SAS) with blockade, paired with a lightweight aluminium chassis, guarantees a smooth ride from birth onward.\n\nThe carrycot features a 100% cotton OEKO-TEX lining, an extendable canopy with panorama-view ventilation window, a 5-position adjustable backrest, carrying handle, rocking rails and 360° reflective piping. The reversible seat unit grows with the child — extendable canopy, 4-position backrest, 5-point harness with magnetic buckle, extendable footrest with water-repellent mud cover, faux leather bumper bar and included footcover.\n\nTwo chassis options: ACTIVE (9.4 kg) with PUR foam rubber wheels (10″ front / 12″ rear), and COMFORT (10.6 kg) with big 32 cm air tires and soft suspension for snowy or muddy terrain. Both feature lightweight aluminium frames, lockable shock absorber system, foldable design with the seat attached, 360° swivelling front wheels, faux leather adjustable handle grip, and a built-in shopping basket.",
"materials": [
"Lightweight aluminium chassis",
"100% cotton OEKO-TEX lining",
"Faux leather handle grip",
"Faux leather bumper bar",
"Magnetic 5-point safety harness",
"Reflective piping (360°)",
"ACTIVE wheels: PUR foam rubber 10″/12″",
"COMFORT wheels: 32 cm air tires with suspension"
],
"dims": "Carrycot 74 × 34 × 21 cm, 4.9 kg • Seat unit 51 × 26 × 23 cm, 4 kg, max child 22 kg • ACTIVE chassis 14.3 kg total, basket 5 kg, folded 34 cm • COMFORT chassis 15.5 kg total, basket 8 kg, folded 41 cm",
"ages": "From birth to ~36 months / max 22 kg",
"certs": [
"OEKO-TEX (cotton lining)"
],
"colors": [
"Brilliant black",
"Garden green",
"Praline beige",
"Dark chocolate",
"Mystic copper",
"Midnight blue",
"Jelly mint"
],
"images": [
"298918_1_mfsjcs.jpg",
"298918_2_tg1ybn.jpg",
"298917_1_kfs1ua.jpg",
"298917_2_l29fir.jpg",
"0443_eixvm6.jpg",
"8808_zqvzz6.jpg",
"8858_jdtlff.jpg",
"8859_qacnep.jpg",
"8912_lqifpa.jpg",
"8913_fezpux.jpg",
"298920_1_fpn8un.jpg",
"298920_2_svf2bz.jpg",
"0557_nd6sy5.jpg",
"0584_qqjuft.jpg",
"298908_1_q4uyhq.jpg",
"298908_2_xsvydq.jpg",
"298908_3_t67wp6.jpg",
"298908_4_zyrrs6.jpg",
"298908_5_af9aei.jpg",
"298908_6_fxr8q0.jpg",
"290981_1_tbbi4j.jpg",
"290981_2_fe2hf8.jpg",
"290981_3_ghxaco.jpg",
"290981_4_h9syni.jpg",
"290981_5_aiqwkp.jpg",
"290981_6_kfd74u.jpg",
"0481_kcv5kl.jpg",
"0532_m99ryc.jpg",
"0468_jomqr4.jpg",
"0520_wgitui.jpg",
"0490_tsgoju.jpg",
"0546_r0o48m.jpg",
"298911_1_hxu1pc.jpg",
"298911_2_u3ol59.jpg",
"298911_3_aqls8l.jpg",
"298911_4_h3px3v.jpg",
"298911_5_dkwmd5.jpg",
"298911_6_icxgce.jpg",
"298910_1_rvkyxo.jpg",
"298910_2_svaxpg.jpg",
"298910_3_ut9zvr.jpg",
"298910_4_odroic.jpg",
"298910_5_oovb8b.jpg",
"298910_6_s49nz9.jpg",
"298909_1_j5dpgq.jpg",
"298909_2_zz5izh.jpg",
"298909_3_kcptmc.jpg",
"298909_4_zhjgrd.jpg",
"298909_5_popm45.jpg",
"298909_6_pua8w5.jpg",
"298907_1_wkupzg.jpg",
"298907_2_ztevtg.jpg",
"298907_3_ntsqin.jpg",
"298907_4_gmlfya.jpg",
"298907_5_cazn0a.jpg",
"298907_6_qcbfld.jpg"
]
},
{
"code": "lux",
"name": "LUX Stroller Set",
"category": "strollers",
"subcategory": "",
"tag": "Luxurious city stroller with flat-folding carrycot",
"description": "Designed for city life, the Tinynord LUX Stroller Set offers all the functionality and luxurious comfort needed to make getting around a busy city more convenient. The set includes a carrycot, seat unit and chassis. A lightweight aluminium chassis with shock absorber system (SAS) plus the carrycot guarantees smooth rides from birth.\n\nThe LUX carrycot features a 100% cotton OEKO-TEX lining, two panorama-view ventilation windows, a carrying handle, a magnetic fastening cover and 360° reflective piping. It is flat-folding for easy transport and storage.\n\nThe LUX seat unit features 100% cotton lining, extendable canopy with panorama-view ventilation window, reflective piping between canopy panels, a multi-position backrest with bamboo inlay reclining flat, 5-point magnetic harness, faux leather bumper bar, footrest with water-repellent mud cover, and an included footcover.\n\nThe LUX chassis is a chrome-finished lightweight aluminium frame (9.1 kg) with black perforated faux leather handle grip, large 100% PUR foam wheels (10″ / 12″), 360° swivelling front wheels with lock, lockable SAS, rear wheel suspension, chassis travel lock, and a magnetic-fastening shopping basket (max 5 kg). Compatible with most infant car seats via adapters (sold separately).",
"materials": [
"Lightweight aluminium chassis (chrome)",
"100% cotton OEKO-TEX lining",
"Bamboo inlay seat backrest",
"Faux leather handle grip (black perforated)",
"Faux leather bumper bar",
"100% PUR foam wheels (10″ / 12″)",
"Magnetic 5-point safety harness",
"360° reflective piping"
],
"dims": "Carrycot 74 × 34 × 26 cm, 4.9 kg • Seat unit length 110 cm, 4 kg, max child 22 kg • Chassis 9.1 kg, total 14 kg, basket 5 kg, folded 34 cm",
"ages": "From birth to ~36 months / max 22 kg",
"certs": [
"OEKO-TEX (cotton lining)"
],
"colors": [
"Caviar black",
"Deep green",
"Sage green",
"Champagne beige"
],
"images": [
"8933_ighvm9.jpg",
"8940_mxadvl.jpg",
"298901_1_fvhrok.jpg",
"298901_2_krxgwd.jpg",
"298901_3_cj69gd.jpg",
"298901_4_pvscp1.jpg",
"298901_5_snjf5t.jpg",
"298901_6_hfjmot.jpg",
"298901_7_w3rjoq.jpg",
"298901_8_kbjujc.jpg",
"298901_9_grljzn.jpg",
"298916_1_msqown.jpg",
"298916_2_sidr7j.jpg",
"298904_1_t0up8i.jpg",
"298904_2_nlyuc5.jpg",
"298904_3_nbk5qp.jpg",
"298904_4_jbfbbm.jpg",
"298904_5_ajgzou.jpg",
"298904_6_bzznnf.jpg",
"298904_7_qikrdy.jpg",
"298904_8_ewi8ug.jpg",
"298904_9_davpjd.jpg",
"298902_1_mrmh95.jpg",
"298902_2_ftlg9c.jpg",
"298902_3_roaoxz.jpg",
"298902_4_lgkrxm.jpg",
"298902_5_jrunut.jpg",
"298902_6_wgibxj.jpg",
"298902_7_qd3kta.jpg",
"298902_8_ga6fmi.jpg",
"298902_9_k3nmbr.jpg",
"298903_1_vwngjm.jpg",
"298903_2_nxyr3j.jpg",
"298903_3_kwwpki.jpg",
"298903_4_ybcikg.jpg",
"298903_5_jf4crf.jpg",
"298903_6_tkezbe.jpg",
"298903_7_ryvalg.jpg",
"298903_8_lx34yq.jpg",
"298903_9_sj7l4y.jpg"
]
}
],
"counts": {
"bathroom": 36,
"eating": 20,
"bedroom": 33,
"clothing": 42,
"car": 12,
"safety": 8,
"stroller-acc": 12,
"strollers": 2
}
};
