// Tinynord catalogue data — products, categories, retailers, copy

const BRAND_COPY = {
  en: {
    nav: { catalogue: 'Catalogue', about: 'About', retailers: 'Retailers', contact: 'Contact' },
    slogan: 'a world of wonders',
    hero: {
      eyebrow: 'From the heart of Estonia',
      title: ['Where every', 'tiny detail', 'matters.'],
      lede: 'Tinynord, a brand originating from the heart of Estonia, was created with the aim of developing and offering baby products that support a child\u2019s early development and ensure safety and comfort for both children and their parents.',
      lede2: 'Our products are characterised by timeless Scandinavian design and a thoughtful selection of materials \u2014 each piece is made of high-quality and durable materials to ensure reliability and long-term use.',
      cta: 'Browse the catalogue',
      featuredLabel: 'Featured this season',
    },
    catalogue: {
      eyebrow: 'The catalogue',
      title: 'Eight categories,\nbuilt for everyday.',
      sub: 'A small, considered range. Designed once, made to last.',
    },
    values: {
      eyebrow: 'Our values',
      title: 'Why families\nchoose Tinynord.',
      items: [
        { t: 'Trustful', b: 'We believe trust is earned in every product we create. Families know they can count on us to be safe, reliable and thoughtfully made.' },
        { t: 'Caring',   b: 'Every product is crafted with heartfelt dedication to support babies during the most important early years.' },
        { t: 'Joyful',   b: 'We believe childhood should be filled with wonders. That\u2019s why we create playful, engaging products that spark imagination.' },
        { t: 'Timeless', b: 'Simple, elegant and practical designs that blend seamlessly into any home. This aesthetic ensures our products remain relevant.' },
        { t: 'Safe',     b: 'Every product we create, from onesies to strollers, is designed and tested to meet the highest safety standards.' },
        { t: 'Cherish',  b: 'We help create moments \u2013 first steps, bedtime giggles, family outings \u2013 our designs are made to be part of treasured memories.' },
      ],
    },
    about: {
      eyebrow: 'About Tinynord',
      title: 'Made for the\nfirst thousand days.',
      body: 'Once upon a time in the heart of Estonia, a brand was born to cater to the needs of the tiniest members of our families. Tinynord was created with a heartfelt mission: to provide premium baby essentials that support a child\u2019s earliest years with care, comfort and style.',
      body2: 'Drawing inspiration from the timeless elegance of Scandinavian design, Tinynord crafts each product with the finest materials \u2014 ensuring durability, sustainability and beauty. From strollers, cozy cribs to the softest clothes, every item is made to be cherished, passed down and loved again.',
      voice: ['Modern & Relatable', 'Clear & Accessible', 'Joyful & Uplifting'],
    },
    retailers: {
      eyebrow: 'Where to buy',
      title: 'Stocked by considered\nretailers across Europe.',
      body: 'Tinynord is sold through a small network of children\u2019s specialists who share our values. Visit them in store or online.',
      empty: 'Becoming a retailer? ',
      emptyLink: 'Get in touch.',
    },
    footer: {
      tagline: 'a world of wonders',
      addr: 'Tinynord O\u00dc \u2014 Tallinn, Estonia',
      cols: { catalogue: 'Catalogue', company: 'Company', contact: 'Contact' },
      legal: '\u00a9 2026 Tinynord O\u00dc. All rights reserved.',
    },
    modal: {
      materials: 'Materials',
      dimensions: 'Dimensions',
      ages: 'Suitable from',
      certifications: 'Certifications',
      gallery: 'Gallery',
    },
  },
  et: {
    nav: { catalogue: 'Tooted', about: 'Lugu', retailers: 'M\u00fc\u00fcjad', contact: 'Kontakt' },
    slogan: 'imede maailm',
    hero: {
      eyebrow: 'Eesti s\u00fcdamest',
      title: ['Iga v\u00e4ike', 'detail', 'loeb.'],
      lede: 'Tinynord on Eesti s\u00fcdamest p\u00e4rit bra\u00e4nd, mis loodi eesm\u00e4rgiga arendada ja pakkuda beebitooteid, mis toetavad lapse varast arengut ning tagavad turvalisuse ja mugavuse nii lastele kui vanematele.',
      lede2: 'Tinynordi tooteid iseloomustab ajatu skandinaavia disain ja l\u00e4bim\u00f5eldud materjalivalik \u2014 iga toode on valmistatud kvaliteetsetest ja vastupidavatest materjalidest.',
      cta: 'Vaata kataloogi',
      featuredLabel: 'Hooaja valik',
    },
    catalogue: {
      eyebrow: 'Kataloog',
      title: 'Kaheksa kategooriat,\niga p\u00e4ev kasutamiseks.',
      sub: 'V\u00e4ike, l\u00e4bim\u00f5eldud valik. Disainitud korra, tehtud kestma.',
    },
    values: {
      eyebrow: 'Meie v\u00e4\u00e4rtused',
      title: 'Miks pered valivad\nTinynordi.',
      items: [
        { t: 'Usaldus',  b: 'Usume, et usaldus tuleb v\u00e4lja teenida iga tootega.' },
        { t: 'Hoolitsus',b: 'Iga toode on loodud s\u00fcdamliku p\u00fchendumusega.' },
        { t: 'R\u00f5\u00f5m',b: 'Usume, et lapsep\u00f5lv peaks olema t\u00e4is imesid.' },
        { t: 'Ajatu',    b: 'Lihtne, elegantne ja praktiline disain.' },
        { t: 'Turvaline',b: 'Iga toode on disainitud k\u00f5rgeimate ohutusstandardite j\u00e4rgi.' },
        { t: 'Hellitus', b: 'Aitame luua hetki, mis j\u00e4\u00e4vad m\u00e4lestustesse.' },
      ],
    },
    about: {
      eyebrow: 'Tinynordist',
      title: 'Esimese tuhande\np\u00e4eva jaoks.',
      body: 'Kunagi ammu Eesti s\u00fcdames s\u00fcndis bra\u00e4nd, mis hoolitseb meie perede k\u00f5ige v\u00e4iksemate liikmete eest.',
      body2: 'Skandinaavia disaini ajatust elegantsist inspireerituna valmistab Tinynord iga toote parimatest materjalidest.',
      voice: ['Modernne & l\u00e4hedane', 'Selge & ligip\u00e4\u00e4setav', 'R\u00f5\u00f5mus & innustav'],
    },
    retailers: {
      eyebrow: 'Kust osta',
      title: 'Valitud poodides\n\u00fcle Euroopa.',
      body: 'Tinynordi m\u00fc\u00fcakse v\u00e4ikese v\u00f5rgustiku kaudu, kes jagavad meie v\u00e4\u00e4rtusi.',
      empty: 'Tahad m\u00fc\u00fcjaks saada? ',
      emptyLink: 'V\u00f5ta \u00fchendust.',
    },
    footer: {
      tagline: 'imede maailm',
      addr: 'Tinynord O\u00dc \u2014 Tallinn, Eesti',
      cols: { catalogue: 'Tooted', company: 'Ettev\u00f5te', contact: 'Kontakt' },
      legal: '\u00a9 2026 Tinynord O\u00dc. K\u00f5ik \u00f5igused kaitstud.',
    },
    modal: {
      materials: 'Materjalid',
      dimensions: 'M\u00f5\u00f5dud',
      ages: 'Sobib alates',
      certifications: 'Sertifikaadid',
      gallery: 'Galerii',
    },
  },
};

const CATEGORIES = [
  { id: 'strollers',    en: 'Strollers',           et: 'Lapsevankrid',        tint: 'lime',  count: 2 },
  { id: 'stroller-acc', en: 'Stroller Accessories',et: 'Vankri tarvikud',     tint: 'beige', count: 2 },
  { id: 'bedroom',      en: 'Bedroom',             et: 'Magamistuba',         tint: 'lightgrey', count: 2 },
  { id: 'bathroom',     en: 'Bathroom',            et: 'Vannituba',           tint: 'beige', count: 2 },
  { id: 'eating',       en: 'Eating Goods',        et: 'S\u00f6\u00f6givahendid', tint: 'lime', count: 2 },
  { id: 'clothing',     en: 'Clothing',            et: 'R\u00f5ivad',         tint: 'lightgrey', count: 2 },
  { id: 'safety',       en: 'Safety Products',     et: 'Turvatooted',         tint: 'beige', count: 2 },
  { id: 'car',          en: 'Car Accessories',     et: 'Auto tarvikud',       tint: 'lime', count: 2 },
];

// Tinynord brand palette — driven by brandbook
const BRAND = {
  lime:      '#D0D15F',
  beige:     '#E3D8D1',
  black:     '#231F20',
  lightgrey: '#F7F1E5',
  grey:      '#959791',
  white:     '#FFFFFF',
};

const PRODUCTS = [
  // STROLLERS
  { id: 'fjord-04', cat: 'strollers', tint: 'lime',
    en: { name: 'Fjord 04 Pram', tag: 'A complete travel system, from newborn to toddler.' },
    et: { name: 'Fjord 04 vanker', tag: 'T\u00e4ielik s\u00fcsteem v\u00e4ikelapsest taadiks.' },
    desc: { en: 'Four configurations \u2014 carrycot, seat, car seat adapter, and toddler stand. Magnesium chassis, all-terrain wheels with PU-foam cushioning, and a one-handed fold designed for narrow Nordic doorways.', et: 'Neli konfiguratsiooni \u2014 vanker, iste, turvahoidja adapter ja v\u00e4ikelapse seismislaud.' },
    materials: ['Magnesium chassis','OEKO-TEX cotton canvas','Recycled aluminium handle'],
    dims: '102 \u00d7 60 \u00d7 95 cm \u2014 12.4 kg',
    ages: '0\u201336 months',
    certs: ['EN 1888-1','EN 1466','OEKO-TEX 100'],
    palette: ['#E3D8D1','#959791','#231F20'],
  },
  { id: 'tundra-go', cat: 'strollers', tint: 'beige',
    en: { name: 'Tundra Go Buggy', tag: 'Light, foldable, made for cobblestones.' },
    et: { name: 'Tundra Go jalutuskaru', tag: 'Kerge, kokkupandav.' },
    desc: { en: 'A 6.8 kg city buggy that folds with one hand and stands on its own. Reclines fully flat and rolls on suspension wheels tuned for the Tallinn old town.', et: 'Linna jalutuskaru kaaluga 6.8 kg.' },
    materials: ['Aluminium alloy frame','OEKO-TEX shadowfabric','Recycled PET basket'],
    dims: '47 \u00d7 30 \u00d7 56 cm folded \u2014 6.8 kg',
    ages: '6\u201348 months',
    certs: ['EN 1888-2','OEKO-TEX 100'],
    palette: ['#F7F1E5','#231F20','#D0D15F'],
  },

  // STROLLER ACCESSORIES
  { id: 'rain-cover', cat: 'stroller-acc', tint: 'lightgrey',
    en: { name: 'Sky Rain Cover', tag: 'Tailored to fit the Fjord 04 and Tundra Go.' },
    et: { name: 'Sky vihmakate', tag: '\u00d5mmeldud Fjord 04 ja Tundra Go jaoks.' },
    desc: { en: 'A clear PU rain cover with a soft trim and a single front zip for ventilation. Folds into a matching pouch the size of a paperback.', et: 'L\u00e4bipaistev PU vihmakate.' },
    materials: ['PFC-free PU','Recycled cotton trim','YKK zippers'],
    dims: 'Universal fit \u2014 packs to 18 \u00d7 12 cm',
    ages: 'All ages',
    certs: ['REACH','OEKO-TEX 100'],
    palette: ['#F7F1E5','#959791','#231F20'],
  },
  { id: 'footmuff-arctic', cat: 'stroller-acc', tint: 'beige',
    en: { name: 'Arctic Footmuff', tag: 'For \u221220 \u00b0C mornings.' },
    et: { name: 'Arctic jalakott', tag: '\u221220 \u00b0C hommikuteks.' },
    desc: { en: 'Recycled wool fleece interior, water-repellent shell, full-length two-way zip. Tested through a Tallinn winter and an Are\u00f6n morning at the lighthouse.', et: 'Ringlussev\u00f5etud villane sisu.' },
    materials: ['Recycled wool fleece','Bluesign\u00ae shell','Cotton lining'],
    dims: '90 \u00d7 45 cm',
    ages: '0\u201336 months',
    certs: ['Bluesign\u00ae','OEKO-TEX 100'],
    palette: ['#E3D8D1','#959791','#231F20'],
  },

  // BEDROOM
  { id: 'moln-cot', cat: 'bedroom', tint: 'beige',
    en: { name: 'Mo\u030aln Convertible Cot', tag: 'A cot, a toddler bed, a junior bed.' },
    et: { name: 'Mo\u030aln muundatav voodi', tag: 'V\u00f5repesa, v\u00e4ikelapse voodi.' },
    desc: { en: 'Solid Estonian birch in a brushed lime-wash. Three heights, two open sides, and a conversion kit included. No exposed hardware.', et: 'Eesti kase massiiv.' },
    materials: ['FSC Estonian birch','Water-based lacquer','Brass fittings'],
    dims: '125 \u00d7 67 \u00d7 88 cm',
    ages: '0\u20136 years',
    certs: ['EN 716','FSC','EU Ecolabel'],
    palette: ['#E3D8D1','#F7F1E5','#231F20'],
  },
  { id: 'cloud-mobile', cat: 'bedroom', tint: 'lime',
    en: { name: 'Cloud Mobile', tag: 'Hand-felted shapes that move with the room.' },
    et: { name: 'Cloud mobiil', tag: 'K\u00e4sitsi vooditud kujundid.' },
    desc: { en: 'Six wool-felt clouds suspended on a turned beech ring. Balanced to drift on the gentlest breeze; never battery-powered, never musical.', et: 'Kuus villasest vildist pilvekest.' },
    materials: ['100% wool felt','FSC beech','Cotton cord'],
    dims: '\u00d8 32 cm \u2014 60 cm drop',
    ages: '0\u201312 months',
    certs: ['EN 71','OEKO-TEX 100'],
    palette: ['#D0D15F','#F7F1E5','#231F20'],
  },

  // BATHROOM
  { id: 'soft-tub', cat: 'bathroom', tint: 'lightgrey',
    en: { name: 'Soft-Tub Baby Bath', tag: 'Silicone, suction-base, dishwasher safe.' },
    et: { name: 'Soft-Tub vann', tag: 'Silikoon, alusega.' },
    desc: { en: 'Food-grade silicone with a non-slip bottom and a low-pour spout for easy emptying. Folds flat for travel.', et: 'Toidusilikoon mittelibiseva p\u00f5hjaga.' },
    materials: ['Food-grade silicone','BPA-free'],
    dims: '76 \u00d7 44 \u00d7 22 cm',
    ages: '0\u201312 months',
    certs: ['LFGB','FDA'],
    palette: ['#F7F1E5','#E3D8D1','#231F20'],
  },
  { id: 'linen-towel', cat: 'bathroom', tint: 'beige',
    en: { name: 'Hooded Linen Towel', tag: 'Stonewashed Estonian linen.' },
    et: { name: 'Kapuutsiga linane r\u00e4tik', tag: 'Pehmestatud Eesti linane.' },
    desc: { en: 'Woven in Tartu from European flax, then stonewashed three times for a softness that ordinary cotton can\u2019t match. Two corners, one hood, no buttons.', et: 'Kootud Tartus Euroopa linast.' },
    materials: ['100% European flax linen'],
    dims: '90 \u00d7 90 cm',
    ages: '0\u20133 years',
    certs: ['European Flax\u00ae','OEKO-TEX 100'],
    palette: ['#E3D8D1','#F7F1E5','#959791'],
  },

  // EATING GOODS
  { id: 'first-bowl', cat: 'eating', tint: 'lime',
    en: { name: 'First Bowl & Spoon', tag: 'Weighted base. Won\u2019t skid, won\u2019t flip.' },
    et: { name: 'Esimene kauss ja lusikas', tag: 'Raskendatud p\u00f5hi.' },
    desc: { en: 'A wide, low silicone bowl with a stoneware-feel weight at the base, paired with a cherry-wood handled spoon sized to a six-month-old\u2019s grip.', et: 'Lai madal silikoonkauss.' },
    materials: ['Food-grade silicone','FSC cherry wood'],
    dims: '\u00d8 14 cm \u2014 spoon 14 cm',
    ages: '6+ months',
    certs: ['LFGB','FSC'],
    palette: ['#D0D15F','#231F20','#F7F1E5'],
  },
  { id: 'sip-cup', cat: 'eating', tint: 'beige',
    en: { name: 'Sip Training Cup', tag: 'A real cup, sized small.' },
    et: { name: 'Sip joogit\u00e4ss', tag: 'P\u00e4ris t\u00e4ss, v\u00e4ike.' },
    desc: { en: 'A 90 ml borosilicate cup with a silicone collar. No spout, no straw, no lid \u2014 the way speech therapists recommend.', et: '90 ml klaasist t\u00e4ss.' },
    materials: ['Borosilicate glass','Food-grade silicone'],
    dims: '\u00d8 6 \u00d7 6 cm \u2014 90 ml',
    ages: '6+ months',
    certs: ['LFGB'],
    palette: ['#E3D8D1','#F7F1E5','#231F20'],
  },

  // CLOTHING
  { id: 'sleep-bag', cat: 'clothing', tint: 'beige',
    en: { name: 'Merino Sleep Bag', tag: 'Year-round. Two togs in one.' },
    et: { name: 'Meriino magamiskott', tag: 'Aastaringne.' },
    desc: { en: 'A Merino jersey shell over a fine-knit liner. Unzip the liner in summer, keep it in for winter. Side zip, fold-over mitts, no tags.', et: 'Meriino kest peene koe voodriga.' },
    materials: ['100% Merino wool','OEKO-TEX cotton liner'],
    dims: 'Sizes 0\u20136, 6\u201318, 18\u201336 mo',
    ages: '0\u201336 months',
    certs: ['ZQ Merino','OEKO-TEX 100'],
    palette: ['#E3D8D1','#F7F1E5','#231F20'],
  },
  { id: 'first-cardigan', cat: 'clothing', tint: 'lightgrey',
    en: { name: 'First Cardigan', tag: 'Knitted in Viljandi from undyed wool.' },
    et: { name: 'Esimene kampsun', tag: 'Kootud Viljandis v\u00e4rvimata villast.' },
    desc: { en: 'A relaxed boxy cut with raglan sleeves and shell buttons. Three natural fleece colours \u2014 oat, ash, mocha \u2014 nothing dyed.', et: 'Vaba l\u00f5ige raglaan-varrukatega.' },
    materials: ['100% undyed Estonian wool','Mother-of-pearl buttons'],
    dims: 'Sizes 56 \u2192 92 cm',
    ages: '0\u201324 months',
    certs: ['Estonian wool mark'],
    palette: ['#F7F1E5','#959791','#231F20'],
  },

  // SAFETY
  { id: 'door-set', cat: 'safety', tint: 'beige',
    en: { name: 'Quiet Door Set', tag: 'Foam stoppers and finger guards.' },
    et: { name: 'Vaikse ukse komplekt', tag: 'Vahust stopperid.' },
    desc: { en: 'A six-piece set: two finger guards, two soft door-stoppers, two corner caps. All in a calm tone that disappears against most walls.', et: 'Kuueosaline komplekt.' },
    materials: ['EVA foam','Recycled silicone'],
    dims: 'Universal fit',
    ages: '6+ months',
    certs: ['EN 71','REACH'],
    palette: ['#E3D8D1','#F7F1E5','#231F20'],
  },
  { id: 'plug-set', cat: 'safety', tint: 'lime',
    en: { name: 'Outlet Plug Set', tag: 'Pinch-proof EU type-F covers.' },
    et: { name: 'Pistikukaitsmete komplekt', tag: 'EU t\u00fc\u00fcp-F kaitsmed.' },
    desc: { en: 'A box of twelve translucent plugs that slot flush against the wall. Tested to 25 N pull-out force. No visible logo.', et: 'Karp 12 l\u00e4bipaistva pistikuga.' },
    materials: ['Recycled ABS'],
    dims: 'EU type F (Schuko)',
    ages: '6+ months',
    certs: ['EN 50075','REACH'],
    palette: ['#D0D15F','#F7F1E5','#231F20'],
  },

  // CAR ACCESSORIES
  { id: 'sun-shade', cat: 'car', tint: 'lime',
    en: { name: 'Linen Sun Shade', tag: 'Two per pack. Static-cling, no suction.' },
    et: { name: 'Linane p\u00e4ikesekate', tag: 'Kaks pakis.' },
    desc: { en: 'A loose-weave linen sun shade that cuts 89 % of UV without darkening the cabin. Static-cling sticks to clean glass for years.', et: 'Linane kate, mis l\u00f5ikab 89 % UV.' },
    materials: ['100% linen','Static-cling backing'],
    dims: '44 \u00d7 36 cm \u00d7 2',
    ages: 'All ages',
    certs: ['UPF 50+','OEKO-TEX 100'],
    palette: ['#D0D15F','#F7F1E5','#231F20'],
  },
  { id: 'mirror', cat: 'car', tint: 'beige',
    en: { name: 'Rear-Seat Mirror', tag: 'Wide angle, shatterproof, tilt-locked.' },
    et: { name: 'Tagaistme peegel', tag: 'Lai vaatenurk.' },
    desc: { en: 'A 24 cm convex mirror in a soft frame. Adjustable head locks in place \u2014 no rattles on cobbles, no glare in headlights.', et: '24 cm kumer peegel.' },
    materials: ['Shatterproof acrylic','Recycled silicone frame'],
    dims: '\u00d8 24 cm',
    ages: '0\u20132 years',
    certs: ['ECE R17'],
    palette: ['#E3D8D1','#231F20','#F7F1E5'],
  },
];

const RETAILERS = [
  { name: 'Nordbaby', url: 'https://nordbaby.com', country: 'Estonia, Latvia, Finland', tagline: 'The flagship retailer.', flag: '\ud83c\uddea\ud83c\uddea', featured: true },
];

window.TINYNORD = { BRAND_COPY, CATEGORIES, PRODUCTS, RETAILERS, BRAND };
